### ISSUE TITLE
Tidying to track tote

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1276]
With support from Russ, I've noticed some parts of the Track Tote that could be clearer.

* Brg Rate (bearing rate) should be moved up, to fall beneath Rel Brg.  Then, all 5 at the top are calculated, and all 4 at the bottom are measured.
* The header titled "Calculation" should be called "Attribute" (since not all are calculated).
* Users can right-click on a calculated value and select "Remove this track".  They should also be able to click on a Secondary Header and receive the "Remove this track" popup menu.
* There's something strange about the text color in the first (Calculation) column. It seems to take the color of the last calculated cell that was printed.  No, that's not right.  I've got **sample.dpf** open.  If I add Nelson as primary, Collingwood as secondary, then the calculation column is in red.  If I then remove Collingwood as secondary, then the calculation column text turns blue.
* We should also investigate what needs fixing in the user guide & tutorial.  Ian will volunteer to do this, but hopefully Russ or Andrew will be up to speed sufficiently to do it.

**Comment by pecko** [comment]
I have created the PR: https://github.com/debrief/debrief/pull/1289

Notices:

- Adding 'Remove this track' to secondary track header 

The action is added only for secondary track.

- Fixing primary track color

I'm not sure what you exactly want. I have changed the code so the "Attribute" column has color of primary track if it exists, otherwise it will use some secondary track's color.

- Fixing a memory leak

You can reproduce the issue in the following way:

- open sample.pdf
- select (open) the Track Tote view
NELSON will be primary track, COLLINGWOOD secondary
- close the Track Tote view
- open the Track Tote view
- try to remove some track (primary or secondary)
You will get the following exception:


!ENTRY org.eclipse.ui 4 0 2015-06-30 20:57:23.800
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4361)
	at org.eclipse.swt.SWT.error(SWT.java:4276)
	at org.eclipse.swt.SWT.error(SWT.java:4247)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:480)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:417)
	at org.eclipse.swt.widgets.Table.setRedraw(Table.java:3145)
	at org.mwc.cmap.tote.views.ToteView.redoTableAfterTrackChanges(ToteView.java:735)
	at org.mwc.cmap.tote.views.ToteView$12.tracksUpdated(ToteView.java:723)
	at org.mwc.cmap.core.DataTypes.TrackData.TrackManager.fireTracksChanged(TrackManager.java:376)
	at org.mwc.cmap.core.DataTypes.TrackData.TrackManager.removeSecondary(TrackManager.java:477)
	at org.mwc.cmap.tote.views.ToteView$11.runWithEvent(ToteView.java:665)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3562)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3186)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

**Comment by IanMayo** [comment]
@pecko  - I've just realised that I missed something in the description here.

Users need to be able to right-click on the header for the Primary to delete it, in addition to the secondary track.

**Comment by pecko** [comment]
I have added the PR: https://github.com/debrief/debrief/pull/1329
