### ISSUE TITLE
NPE in TimeController view

### ISSUE THREAD

**Issue by pecko** [debrief/debrief#1348]
Try the following:

- open a plot (sample.pdf, for instance)
- open the Time Controller view
- click the Play button
- close the editor while the Time Controller play

You will get the following exception:

!ENTRY java.lang.NullPointerException
org.mwc.cmap.core 4 0 2015-09-12 22:34:04.712
!MESSAGE Error on auto-time stepping
!STACK 0
java.lang.NullPointerException
	at org.mwc.cmap.TimeController.views.TimeController.processClick(TimeController.java:889)
	at org.mwc.cmap.TimeController.views.TimeController.onTime(TimeController.java:784)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)
	at org.mwc.cmap.TimeController.views.TimeController.processClick(TimeController.java:889)
	at org.mwc.cmap.TimeController.views.TimeController.onTime(TimeController.java:784)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)

!ENTRY java.lang.NullPointerException
	at org.mwc.cmap.TimeController.views.TimeController.processClick(TimeController.java:889)
	at org.mwc.cmap.TimeController.views.TimeController.onTime(TimeController.java:784)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)

It will not stop if you try click the Stop(Pause) button, close the Time Controller view ...
Only workaround is restarting the Debrief.

**Comment by pecko** [comment]
The PR: https://github.com/debrief/debrief/pull/1349

**Comment by IanMayo** [comment]
Fixed in #1349
