### ISSUE TITLE
Double click on Chart view to maximize throws NPE

### ISSUE THREAD

**Issue by sambireddyt** [debrief/debrief#1702]
!ENTRY org.eclipse.ui 4 0 2016-04-20 01:35:25.307
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.mwc.cmap.gt2plot.proj.GtProjection.toWorld(GtProjection.java:223)
	at org.mwc.cmap.overview.views.ChartOverview.paintDataRect(ChartOverview.java:284)
	at org.mwc.cmap.overview.views.ChartOverview$2.paintMe(ChartOverview.java:158)
	at org.mwc.cmap.plotViewer.editors.chart.SWTCanvas.paintPlot(SWTCanvas.java:436)
	at org.mwc.cmap.plotViewer.editors.chart.SWTCanvas.repaintMe(SWTCanvas.java:369)
	at org.mwc.cmap.plotViewer.editors.chart.SWTCanvas$4.paintControl(SWTCanvas.java:258)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:230)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)

**Comment by IanMayo** [comment]
Does this happen every time you double-click on the Chart? If it doesn't , could you include steps to reproduce?

**Comment by sambireddyt** [comment]
Yes. I can reproduce it consistently. 
1. open any .rep file
2. go to chart view
3. double click on view title.
