### ISSUE TITLE
Bug in Changing Solution start time

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#1784]
I'm doing tutorial 4, specifically creating the manual solution.

I've broken the data into three legs.  But, when I change the start time of leg one, I get an NPE:
````
	at org.mwc.cmap.gt2plot.proj.GtProjection.toScreen(GtProjection.java:189)
	at org.mwc.cmap.core.ui_support.swt.SWTCanvasAdapter.toScreen(SWTCanvasAdapter.java:343)
	at Debrief.Wrappers.TrackWrapper.paintFixes(TrackWrapper.java:2655)
	at Debrief.Wrappers.TrackWrapper.paint(TrackWrapper.java:2966)
	at org.mwc.debrief.core.editors.painters.PlainHighlighter.paintThisLayer(PlainHighlighter.java:100)
````

I'm pretty sure this is related to the deferred generation of TMA positions until the paint operation.  But, Debrief is failing when it encounters the null position(s).

The error occurs if a track is extended or shortened.

Treat this as a high priority.

**Comment by IanMayo** [comment]
We have an emergent bug related to this.

If the user tries to set the solution start time before the start of the blue track, the solution is effectively corrupted.

Debrief needs to handle this more robustly
