### ISSUE TITLE
Create TrackSegment - not possible to change label location

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2052]
An analyst is manually producing track segments - using the *Create track segment* on the main toolbar.

But, when these segments are in the Outline view, they can't be expanded.  This prevents (amongst other things) the ability to open the layer and view segments, so particular ones can have their location changed.

Ooh, we should also check that we do our intelligent "choose label location" processing for manually added track segments.

**Comment by IanMayo** [comment]
@theanuradha - I'm having a real battle with this one.   I'd appreciate your help in debugging what's happening.

I've started the changed, and pushed it to a branch in your REPO (PR [here](https://github.com/debrief/debrief/pull/2057) ).  But, I'm getting an "Array Index out of Bounds" exception that I just can't understand.

Here are the steps to reproduce:
* open **boat2.rep**
* click on the *Track Segment* icon on the toolbar,  It's two to the left of the *Natural Earth* globe shape.
* From the popup dialog, select **[New Track...]**
* Enter **Test track** as the name for the new track
* Accept the provided date as the start date
* Call it **Leg one**
* The new track (and new leg) will be be displayed in red, and expanded in the Outline view.
* Click on a child position within **Leg one** in the Outline view
* An exception is thrown. The exception is also thrown if you right-click on one of the child items and change something from the popup menu (such as label showing)

````
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.eclipse.ui.views.properties.PropertySheetViewer.updateChildrenOf(PropertySheetViewer.java:1309)
	at org.eclipse.ui.views.properties.PropertySheetViewer.updateChildrenOf(PropertySheetViewer.java:1312)
	at org.eclipse.ui.views.properties.PropertySheetViewer.access$2(PropertySheetViewer.java:1211)
	at org.eclipse.ui.views.properties.PropertySheetViewer$3.childEntriesChanged(PropertySheetViewer.java:322)
	at org.eclipse.ui.views.properties.PropertySheetEntry.fireChildEntriesChanged(PropertySheetEntry.java:301)
	at org.eclipse.ui.views.properties.PropertySheetEntry.refreshChildEntries(PropertySheetEntry.java:576)
	at org.eclipse.ui.views.properties.PropertySheetEntry.setValues(PropertySheetEntry.java:760)
	at org.eclipse.ui.views.properties.PropertySheetViewer.setInput(PropertySheetViewer.java:973)
	at org.eclipse.ui.views.properties.PropertySheetPage.refresh(PropertySheetPage.java:491)
	at org.mwc.cmap.plotViewer.editors.CorePlotEditor$18.run(CorePlotEditor.java:1359)
````

**Comment by IanMayo** [comment]
It's a really tricky one @theanuradha .  If you don't have any success I'll carry on looking into it tomorrow.  It's strange - but these new fixes seem to have their own properties plus those of the parent. 

As I said, I'll be looking into it tomorrow.

**Comment by IanMayo** [comment]
Fixed it.  Really tricky.  The problem was this:
* when we get properties for a Fix, we also return the properties for the parent
* PlanningSegment "legs" have a property for label format.  
* This property has the same label as the property for the fix in the leg "Label Format"
* Changing the leg property name fixes the issue.
