### ISSUE TITLE
Classic - possible threading issues in rendering

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2155]
Steps to reproduce:
* open `DebriefApp`
* use `File / Import Replay`, then navigate to `boat1.rep`

Exception thrown:
`
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.GUI.Canvas.Swing.SwingCanvas.setLineStyle(SwingCanvas.java:718)
	at Debrief.Wrappers.TrackWrapper.paintSetOfPositions(TrackWrapper.java:3247)
	at Debrief.Wrappers.TrackWrapper.paintFixes(TrackWrapper.java:2831)
	at Debrief.Wrappers.TrackWrapper.paint(TrackWrapper.java:3110)
	at MWC.GUI.Chart.Swing.SwingChart.paintMe(SwingChart.java:409)
	at MWC.GUI.Canvas.Swing.SwingCanvas.paintIt(SwingCanvas.java:1050)
`

It looks like `endDraw` is being called before the rendering has finished.  If so, this could be a threading issue.

**Comment by theanuradha** [comment]
https://github.com/debrief/debrief/pull/2159

**Comment by IanMayo** [comment]
Re-open, I'd like to gain an understanding of what is causing the multi-thread repainting.
