### ISSUE TITLE
GeoTiff not loading

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2372]
IH has some GeoTiff files.

They all load without errors.  But, some don't appear in Debrief.  Investigate.

**Comment by IanMayo** [comment]
The original failure was because the file had an uppercase .TIF suffix.

That's fixed in #2379 - but we still get an exception thrown:

````
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:225)
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:157)
	at org.mwc.cmap.gt2plot.data.WorldImageLayer.loadLayer(WorldImageLayer.java:80)
	at org.mwc.cmap.gt2plot.data.GeoToolsLayer.setMap(GeoToolsLayer.java:107)
	at org.mwc.cmap.gt2plot.proj.GtProjection.addGeoToolsLayer(GtProjection.java:516)
	at org.mwc.cmap.plotViewer.editors.CorePlotEditor$3.addThisLayer(CorePlotEditor.java:350)
	at org.mwc.debrief.core.loaders.TifLoader$1.run(TifLoader.java:89)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)
Caused by: org.geotools.data.DataSourceException
	at org.geotools.gce.geotiff.GeoTiffReader.getHRInfo(GeoTiffReader.java:412)
	at org.geotools.gce.geotiff.GeoTiffReader.<init>(GeoTiffReader.java:212)
	... 7 more
Caused by: java.lang.NullPointerException
	at org.geotools.referencing.cs.AbstractCS.axisUsingUnit(AbstractCS.java:511)
	at org.geotools.referencing.cs.DefaultCartesianCS.usingUnit(DefaultCartesianCS.java:302)
	at org.geotools.coverage.grid.io.imageio.geotiff.GeoTiffMetadata2CRSAdapter.createUserDefinedPCS(GeoTiffMetadata2CRSAdapter.java:758)
	at org.geotools.coverage.grid.io.imageio.geotiff.GeoTiffMetadata2CRSAdapter.createProjectedCoordinateReferenceSystem(GeoTiffMetadata2CRSAdapter.java:271)
	at org.geotools.coverage.grid.io.imageio.geotiff.GeoTiffMetadata2CRSAdapter.createCoordinateSystem(GeoTiffMetadata2CRSAdapter.java:206)
	at org.geotools.gce.geotiff.GeoTiffReader.getHRInfo(GeoTiffReader.java:300)
	... 8 more
````

**Comment by IanMayo** [comment]
So, hypothesis one is we're missing some data.

Here are the two types of geo file that we can plot:
- a GeoTiff file has the coordintes (and projection) written inside the file 
-or it is a WorldImage file (ie normal TIFF + Coordiantes + PRJ file) 

Maybe the working file is a GeoTiff, but this is a normal Tiff.

**Comment by IanMayo** [comment]
Ok, I'm stumped on this.  I was able to use the QGis browser to examine the metadata on the images.

Screenshots of the metadata is shown below.  The image on the right is the sort we've received in the past.  The origin shown is approximately correct.  In Debrief, the distance from this area down to the equator is approximately 7 million metres. 

The geotiff on the right correctly loads into Debrief, and is shown in the correct location (the coastline snippets line up with those shown from Natural Earth).

The HiRes image seems to have a different origin.  But, the HiRes image doesn't get shown in the wrong location - it throws the above exception when Debrief (well, GeoTools) is trying to load it.  It looks like there is some other inconsistency.

![combinedqgis_reports](https://user-images.githubusercontent.com/1108513/29170243-7aa4d278-7dcf-11e7-89b5-b2a7ad7f27c1.png)

**Comment by IanMayo** [comment]
GIS consultancy required to understand why data units twice that expected.  A workaround can then be devised.

**Comment by IanMayo** [comment]
Fixed in #5230
