### ISSUE TITLE
M19.7 Invalid thread access exception while changing image selection from timecontroller

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#2984]
An invalid thread access exception is being thrown consistently when timecontroller time changes to show new images.
Steps to reproduce:
1. Open the image viewer and open the folder containing images
2. Activate sample.dpf in the plot editor and click play on the time controller.
3. Following exception is thrown:
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:373)
	at org.eclipse.swt.widgets.Control.isVisible(Control.java:2024)
	at org.mwc.cmap.media.views.images.ImageLoader$ImagePanelLoader.<init>(ImageLoader.java:152)
	at org.mwc.cmap.media.views.images.ImageLoader.load(ImageLoader.java:78)
	at org.mwc.cmap.media.views.ImagesView.selectImage(ImagesView.java:456)
	at org.mwc.cmap.media.views.ImagesView.selectImage(ImagesView.java:601)
	at org.mwc.cmap.media.views.ImagesView.access$0(ImagesView.java:581)
	at org.mwc.cmap.media.views.ImagesView$1.propertyChange(ImagesView.java:115)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at org.mwc.cmap.core.DataTypes.Temporal.TimeManager.setTime(TimeManager.java:77)
	at org.mwc.cmap.TimeController.views.TimeController.fireNewTime(TimeController.java:1076)
	at org.mwc.cmap.TimeController.views.TimeController.processClick(TimeController.java:989)
	at org.mwc.cmap.TimeController.views.TimeController.onTime(TimeController.java:785)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)

**Comment by IanMayo** [comment]
Fixed, by @ayeshare
