### ISSUE TITLE
An  exception in narrative viewer when loaded FCS Narrative

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#3071]
In the dev mode, I opened boat1.rep and dragged the FCS_Narrative.doc from the sample_data/otherformats and dropped on to the plot editor. 

The narrative viewer opens with the error:
java.lang.NullPointerException
	at org.mwc.cmap.NarrativeViewer2.FilteredNatTable.createClearTextNew(FilteredNatTable.java:256)
	at org.mwc.cmap.NarrativeViewer2.FilteredNatTable.createFilterControls(FilteredNatTable.java:453)
	at org.mwc.cmap.NarrativeViewer2.FilteredNatTable.createControl(FilteredNatTable.java:425)
	at org.mwc.cmap.NarrativeViewer2.FilteredNatTable.init(FilteredNatTable.java:861)
	at org.mwc.cmap.NarrativeViewer2.FilteredNatTable.<init>(FilteredNatTable.java:230)
	at org.mwc.cmap.NarrativeViewer2.NatNarrativeViewer$1.<init>(NatNarrativeViewer.java:158)
	at org.mwc.cmap.NarrativeViewer2.NatNarrativeViewer.<init>(NatNarrativeViewer.java:158)
	at org.mwc.cmap.NarrativeViewer2.NATViewerView.createPartControl(NATViewerView.java:489)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:147)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)

**Comment by ayeshare** [comment]
This is not consistent. I cannot replicate this now.

**Comment by ayeshare** [comment]
Steps to reproduce:
Start with a new debrief workspace.  Add the sample data manually in a new project.
Open boat1.rep from the sample data.  Drop FCSnarrative.doc to the plot editor. in the popup choose all or trim and click ok.   When the narrative viewer opens, the above error shows up.

**Comment by IanMayo** [comment]
@ayeshare - I presume this only occurs in your development branch: `2960_trimnarratives_offer` (because it relies on the popup opening)

**Comment by IanMayo** [comment]
Sadly, I can't reproduce this, under OSX or MS WIN.  Could you watch this screen-recording, and verify I'm following the correct steps?

https://youtu.be/TJowlgiKwas

**Comment by ayeshare** [comment]
This is fixed now after using local images instead of images from eclipse internal plugins.
