### ISSUE TITLE
Silently fails importing REP data with invalid month - Debrief should display message when it gets invalid data to open

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3244]
### Steps to Reproduce :
1. Open boat1.rep with Text Editor (_right click, open with...)
2. Change the month in the fourth row to 00
3. Save and close
4. Open boat1.rep with Debrief Plot Editor

When it tries to open the above data with Debrif plot editor , it logs the below exception but Debrief doesn't return any message to the user, it seems it is opening the file by showing busy cursor but it never opened it. After this operation,Debrief can't be turned to working state, and I only can terminate Debrief from eclipse and launched it again.
java.text.ParseException: Unparseable date: "950012 050300"
        at java.text.DateFormat.parse(Unknown Source)
        at MWC.Utilities.TextFormatting.DebriefFormatDateTime.parseThis(DebriefFormatDateTime.java:288)
        at MWC.Utilities.TextFormatting.DebriefFormatDateTime.parseThis(DebriefFormatDateTime.java:355)
        at Debrief.ReaderWriter.Replay.ImportFix.readThisLine(ImportFix.java:211)
[..]
        at org.mwc.debrief.core.loaders.ReplayLoader$2.run(ReplayLoader.java:152)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
java.text.ParseException: Unparseable date: "950012 050300"
        at java.text.DateFormat.parse(Unknown Source)
        at MWC.Utilities.TextFormatting.DebriefFormatDateTime.parseThis(DebriefFormatDateTime.java:288)
        at MWC.Utilities.TextFormatting.DebriefFormatDateTime.parseThis(DebriefFormatDateTime.java:355)
[..]
        at org.mwc.debrief.core.loaders.ReplayLoader$2.run(ReplayLoader.java:152)
        at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

And after long waiting, Debrief still is busy trying to open the editor, I can only terminate Debrief to continue other work so doing that I get NPE as both with dialog and error log :  java.lang.NullPointerException
        at org.mwc.cmap.plotViewer.editors.CorePlotEditor.dispose(CorePlotEditor.java:620)
        at org.mwc.debrief.core.editors.PlotEditor.dispose(PlotEditor.java:1130)
        at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:264)
[..]
        at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:81)
        at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:114)
[..]
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)

### Expected Result:
It should display a message to user that it can't open the file due to its invalid data. Debrief should be communicable enough to its users

**Comment by helenayele** [comment]
In My current tests, I can see the import error dialog https://gyazo.com/381de1d5dc2f7f01b0ca3dd4519da5e0 whenever I tried to open the plot. 

### Steps:
1. Open boat1.rep with Text Editor
2. Change the month in the fourth row to 00
3. Save and close
4. Open boat1.rep with Debrief Plot Editor , I can see the dialog  https://gyazo.com/381de1d5dc2f7f01b0ca3dd4519da5e0 and pressing okay will try to open the plot 
5. close the opened plot
6.  Repeat step 4-5  four or 5 time
7 . After that Debrief goes to busy state. 
I Suggest that for invalid data, don't try open the plot.

**Comment by helenayele** [comment]
It is now fixed, trying to re-open as many times as possible doesn't bring any issue and working as expected. Hence closing..
