### ISSUE TITLE
M27.2 Select new icons from REP file symbology- NullPointerException while using icons from SVG

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3245]
### Steps to Reproduce :
1. Open boat1 file with text editor and replace every @C with @C[SYMBOL=Coastguard]
2. Save and try to open with Debrief Plot Editor
3. See that it didn't open it instead it throws :
!MESSAGE Exception caught:Failed to create symbol, string type:svg:Coastguard not found

!ENTRY org.mwc.debrief.core 4 0 2018-10-03 14:01:01.316
!MESSAGE Problem loading datafile:D:\Debrief\Debrief_ws\my_plot_project\sample_data\boat1.rep
!STACK 0
java.lang.NullPointerException
	at Debrief.Wrappers.Track.LightweightTrackWrapper.setSymbolType(LightweightTrackWrapper.java:454)
	at Debrief.ReaderWriter.Replay.ImportReplay.processReplayFix(ImportReplay.java:2034)
	at Debrief.ReaderWriter.Replay.ImportReplay.readLine(ImportReplay.java:2237)
	at Debrief.ReaderWriter.Replay.ImportReplay.importRep(ImportReplay.java:1545)
	at Debrief.ReaderWriter.Replay.ImportReplay.importThis(ImportReplay.java:1499)
	at MWC.Utilities.ReaderWriter.PlainImporterBase.importThis(PlainImporterBase.java:128)
	at org.mwc.debrief.core.loaders.ReplayLoader.doTheLoad(ReplayLoader.java:111)
	at org.mwc.debrief.core.loaders.ReplayLoader.access$0(ReplayLoader.java:102)
	at org.mwc.debrief.core.loaders.ReplayLoader$2.run(ReplayLoader.java:152)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

!ENTRY org.mwc.debrief.core 1 0 2018-10-03 14:01:01.446
!MESSAGE Successfully loaded REPLAY file
java.lang.NullPointerException
	at Debrief.Wrappers.Track.LightweightTrackWrapper.setSymbolType(LightweightTrackWrapper.java:454)
	at Debrief.ReaderWriter.Replay.ImportReplay.processReplayFix(ImportReplay.java:2034)
	at Debrief.ReaderWriter.Replay.ImportReplay.readLine(ImportReplay.java:2237)
	at Debrief.ReaderWriter.Replay.ImportReplay.importRep(ImportReplay.java:1545)
	at Debrief.ReaderWriter.Replay.ImportReplay.importThis(ImportReplay.java:1499)
	at MWC.Utilities.ReaderWriter.PlainImporterBase.importThis(PlainImporterBase.java:128)
	at org.mwc.debrief.core.loaders.ReplayLoader.doTheLoad(ReplayLoader.java:111)
	at org.mwc.debrief.core.loaders.ReplayLoader.access$0(ReplayLoader.java:102)
	at org.mwc.debrief.core.loaders.ReplayLoader$2.run(ReplayLoader.java:152)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Oct 03, 2018 2:01:25 PM org.geotools.referencing.operation.projection.Mercator1SP.Inverse transform
WARNING: Possible use of ""Mercator_1SP (Inverse transform)"" projection outside its valid area.
Longitude 290°40.0'W is out of range (±180°).

### Expected Result:
New icons from REP file symbology should be rendered without any issues.

**Comment by helenayele** [comment]
I also tried to replace  @C with  @C[SYMBOL=svg:countermeasure]  but still Debrief couldn't open the editor - SS :  https://gyazo.com/15497fc80ecc61da32c81397cac1ad60

Data - https://gyazo.com/dcfae4e1366fc048aef0247f65198966

**Comment by helenayele** [comment]
[stackTrace_fullLog.txt](https://github.com/debrief/debrief/files/2473157/stackTrace_fullLog.txt)
Full stack trace while trying to open the above file in Debrief plot editor

**Comment by IanMayo** [comment]
@helenayele - found one of the issues.

There isn't a `coastguard`, but there is a `coastguard_law_enforcement`.  So this line works:
````
951212 111000.000 NELSON  @C[SYMBOL=Coastguard_law_enforcement]   22  7  4.88 N 21 45 18.94 W  58.5   2.0      0 
````

The other issue is that it's `countermeasure` not `svg:countermeasure`.

The full names are here:
http://www.debrief.info/tutorial/symbol_sets.html#more_sym_sets

BTW - I'm improving the way it handles symbol not found, so it doesn't just crash.

Would you mind checking the above?  If it's all ok, please close it.

**Comment by helenayele** [comment]
It is now working and looks like https://gyazo.com/55824921e6452c4b3b71df4a815d3a6b with @C[SYMBOL=Coastguard_law_enforcement]

**Comment by IanMayo** [comment]
FYI - you can view the symbol on the plot by changing the plot highlighter to `symbol highlight`:
![image](https://user-images.githubusercontent.com/1108513/46877034-b5989900-ce37-11e8-82d0-f37723ef9014.png)
