### ISSUE TITLE
NullPointerException is logged while saving rep file to dpf

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3333]
### Steps to reproduce:
1. In sample_data project, open nosuch.rep file from S2R folder
2. Save as  .dpf file , give any name you like. 
See that the file is renamed but it logs the below Null pointer exception:
!ENTRY org.eclipse.ui 4 0 2018-10-23 12:38:06.285
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.mwc.debrief.core.editors.PlotEditor$17.run(PlotEditor.java:2484)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by ayeshare** [comment]
cant replicate this now, I tried this with the steps to reproduce given above.

**Comment by IanMayo** [comment]
Ok, this extra detail makes it look like a Grid Editor NPE issue. Hopefully the extra steps will enable @ayeshare  to reproduce it.

**Comment by ayeshare** [comment]
even with the exact same steps i cant reproduce it

**Comment by IanMayo** [comment]
Nope, I can't reproduce it either.  Helen, could you record a video of the steps to reproduce it, please?

**Comment by helenayele** [comment]
Sure here is the video 

[NPE_while_saving_rep.zip](https://github.com/debrief/debrief/files/2528776/NPE_while_saving_rep.zip)

**Comment by IanMayo** [comment]
Thanks @helenayele - I'll have another go at reproducing it later.

**Comment by helenayele** [comment]
Not reproducible at my side as well ,so closing...
