### ISSUE TITLE
Issue when exporting Scale to WMF

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3358]
When the Scale is selected in the PropertiesView, it fails to write to WMF.

It looks like we need to fire the update in the UI Thread:
````
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Display.error(Display.java:1090)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:632)
	at org.eclipse.swt.widgets.Display.timerExec(Display.java:4900)
	at org.eclipse.swt.custom.TreeEditor.resize(TreeEditor.java:230)
	at org.eclipse.swt.custom.TreeEditor.setItem(TreeEditor.java:272)
	at org.eclipse.swt.custom.TreeEditor.setEditor(TreeEditor.java:288)
	at org.eclipse.ui.views.properties.PropertySheetViewer.deactivateCellEditor(PropertySheetViewer.java:411)
	at org.eclipse.ui.views.properties.PropertySheetViewer.setInput(PropertySheetViewer.java:967)
	at org.eclipse.ui.views.properties.PropertySheetPage.refresh(PropertySheetPage.java:539)
	at org.mwc.debrief.core.editors.PlotPropertySheetPage$1.propertyChange(PlotPropertySheetPage.java:73)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at MWC.GUI.Editable$EditorType.fireChanged(Editable.java:555)
	at MWC.GUI.Chart.Painters.ScalePainter.paint(ScalePainter.java:540)
	at MWC.GUI.Plottables.paint(Plottables.java:330)
````

**Comment by IanMayo** [comment]
Done.
