### ISSUE TITLE
NullPointerException while invoking toolbar menus on Time controller view in non existent of opened editors

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3389]
When we open Time Controller view for the first time, and there is no any plot opened , the toolbar items like Normal, Snail, Filter Plot data..,etc are not shown at all  - [![Image from Gyazo](https://i.gyazo.com/de91bb1cbb32a594ef031c5025270ff5.png)](https://gyazo.com/de91bb1cbb32a594ef031c5025270ff5) and this fine. 
But if a user opened a plot, those toolbar items will stay visible even if  the opened plot is closed. 
[![Image from Gyazo](https://i.gyazo.com/26a3a1ffb3d78dac2b6b2408afb3c0c1.png)](https://gyazo.com/26a3a1ffb3d78dac2b6b2408afb3c0c1) - after opening and closing editor
And if user selects Snail mode, the below NPE is silently logged.
### Steps to Reproduce

1.  If debrief is opned in clean workspace, or no plot was opned before ,open sample.dpf or any other file
2. Close all opned plots
3. Invoke Snail / Normal  mode

java.lang.NullPointerException
	at org.mwc.cmap.TimeController.views.TimeController.createPainterOptions(TimeController.java:1309)
	at org.mwc.cmap.TimeController.views.TimeController.populateDropDownList(TimeController.java:2026)
	at org.mwc.cmap.TimeController.views.TimeController.access$22(TimeController.java:2005)
	at org.mwc.cmap.TimeController.views.TimeController$10$1.run(TimeController.java:1324)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3933)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3564)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
And if I click drop-down view menu > DTG Format > and select one of the availble format the below exception will be logged

java.lang.NullPointerException
	at org.mwc.cmap.TimeController.views.TimeController$41$1.propertyChange(TimeController.java:3005)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at org.mwc.cmap.core.DataTypes.Temporal.TimeControlProperties.fireChange(TimeControlProperties.java:304)
	at org.mwc.cmap.core.DataTypes.Temporal.TimeControlProperties.setPropertyValue(TimeControlProperties.java:281)
	at org.mwc.cmap.TimeController.views.TimeController$3.run(TimeController.java:953)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

### Expected Result:
If there is no any opened editors to apply those actions , it is better to hide all toolbar items.

**Comment by IanMayo** [comment]
The toolbar items are correctly being removed.  Nice.

But, there's still an exception if the "Filter to time period" toggle button is clicked:
````
!ENTRY org.eclipse.ui 4 0 2018-11-20 11:19:46.979
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.mwc.cmap.TimeController.views.TimeController$FilterToPeriodAction.run(TimeController.java:136)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
````

**Comment by helenayele** [comment]
Verified -  Currently when we close all editors , the toobar buttons on the timecontroller view will be closed as well. so no way to get those buttons on blank editor.

**Comment by helenayele** [comment]
I get this exception logged following these steps
Make sure that all editors are closed
Drag sensor or brt sensors files on the editor
See that a dialog that tells the user to open at least 1 track is shown 
click okay, but this time the sensor is opened in a plot like
[![Image from Gyazo](https://i.gyazo.com/e31b347e4b0fe413f82ef32f33c9c019.png)](https://gyazo.com/e31b347e4b0fe413f82ef32f33c9c019)

And see the time controllers toobar buttons they all are displayed and enabled .
So clicking Dropdown menu > DTG Format > select one of the format , will throw null pointer exception.

**Comment by IanMayo** [comment]
Ooh, you're good @helenayele .

I'll take this one.

**Comment by helenayele** [comment]
And it is better to disable those time related buttons unless we have track /time data on the plot.
