### ISSUE TITLE
RuntimeException is logged while interacting in the maintain contributions view

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3444]
"WARNING: Prevented recursive attempt to activate part org.eclipse.ui.views.PropertySheet while still in the middle of activating part " with the below stack trace is logged while:
1. Clicking inside the maintain contributions view , after renaming  scenario in property view  
2. Clicking Calculate Solution button - during solution generation.
#### Stack Trace:
java.lang.RuntimeException: WARNING: Prevented recursive attempt to activate part org.eclipse.ui.views.PropertySheet while still in the middle of activating part com.planetmayo.debrief.satc_rcp.views.MaintainContributionsView
	at org.eclipse.ui.internal.WorkbenchPage.setActivePart(WorkbenchPage.java:3599)
	at org.eclipse.ui.internal.WorkbenchPage.requestActivation(WorkbenchPage.java:3172)
	at org.eclipse.ui.internal.PartPane.requestActivation(PartPane.java:281)
	at org.eclipse.ui.internal.PartPane.handleEvent(PartPane.java:239)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1077)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1058)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1447)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2836)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2417)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5152)
	at org.eclipse.swt.widgets.Tree.WM_SETFOCUS(Tree.java:7083)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4598)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:5977)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4976)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1098)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3303)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1040)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1038)
	at org.eclipse.swt.widgets.Control.fixFocus(Control.java:1053)
	at org.eclipse.swt.widgets.Control.setVisible(Control.java:3762)
	at org.eclipse.ui.part.PageBook.showPage(PageBook.java:111)
	at org.eclipse.ui.part.PageBookView.showPageRec(PageBookView.java:988)
	at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:767)
	at org.eclipse.ui.views.properties.PropertySheet.partActivated(PropertySheet.java:325)
	at org.eclipse.ui.part.PageBookView$4.partActivated(PageBookView.java:1023)
	at org.eclipse.ui.internal.PartListenerList2$1.run(PartListenerList2.java:70)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.runtime.Platform.run(Platform.java:857)
	at org.eclipse.ui.internal.PartListenerList2.fireEvent(PartListenerList2.java:55)
	at org.eclipse.ui.internal.PartListenerList2.firePartActivated(PartListenerList2.java:68)
	at org.eclipse.ui.internal.PartService.firePartActivated(PartService.java:192)
	at org.eclipse.ui.internal.PartService.setActivePart(PartService.java:306)
	at org.eclipse.ui.internal.WorkbenchPagePartList.fireActivePartChanged(WorkbenchPagePartList.java:57)
	at org.eclipse.ui.internal.PartList.setActivePart(PartList.java:136)
	at org.eclipse.ui.internal.WorkbenchPage.setActivePart(WorkbenchPage.java:3649)
	at org.eclipse.ui.internal.WorkbenchPage.requestActivation(WorkbenchPage.java:3172)
	at org.eclipse.ui.internal.PartPane.requestActivation(PartPane.java:281)
	at org.eclipse.ui.internal.presentations.PresentablePart.setFocus(PresentablePart.java:192)
	at org.eclipse.ui.internal.presentations.util.TabbedStackPresentation$1.handleEvent(TabbedStackPresentation.java:94)
	at org.eclipse.ui.internal.presentations.util.AbstractTabFolder.fireEvent(AbstractTabFolder.java:269)
	at org.eclipse.ui.internal.presentations.util.AbstractTabFolder.fireEvent(AbstractTabFolder.java:274)
	at org.eclipse.ui.internal.presentations.util.AbstractTabFolder.handleMouseDown(AbstractTabFolder.java:344)
	at org.eclipse.ui.internal.presentations.util.AbstractTabFolder$3.mouseDown(AbstractTabFolder.java:78)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:192)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1438)

**Comment by IanMayo** [comment]
@helenayele  - is anything shown to the user when this happens?

It seems like an internal Eclipse thing. We get it every now and then, but since it's normally invisible to the user we live with it.

**Comment by helenayele** [comment]
Nothing is shown to the user, it is just silently logged.
