### ISSUE TITLE
Divide by 0 Exception while using Resample sensor data functionality 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3451]
### Steps to Reproduce

1. Copy All Tracks.rep from [brt_import.zip](https://github.com/debrief/debrief/files/2545122/brt_import.zip) to your Project and Drag in to the plot

2. Use default values for Sensor Import wizard and complete the wizard
3. Make all sensor data visible
4. Open Sensor layer and right click on Sensor:tail sensor(  cuts) layer > tail sensor > Resample data at > 15 min 
5. Then I get all sensor cuts disappeared from the plot.
6. Tried to change teh resample data at > all  and also at none - then finally I get the below exception logged
Plot Screenshot : [![Image from Gyazo](https://thumb.gyazo.com/thumb/200/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbWciOiJfZTAyOTdkYTEyZDdjNjAwODViYmQ3ZGI0NTQyOGQwOTQifQ.v0j1ssfjBtHHUR5zJ7x8id95kklMglSSBjU_3V5_mzw-png.jpg)](https://gyazo.com/bd8165b2bc1f1cc2688a7f154e1fd583)

Error Message : Setter call failed:tail sensor Error was:/ by zero
java.lang.ArithmeticException: / by zero
	at Debrief.Wrappers.SensorWrapper.setResampleDataAt(SensorWrapper.java:482)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mwc.cmap.core.property_support.RightClickSupport$ListPropertyAction.doIt(RightClickSupport.java:137)
	at org.mwc.cmap.core.property_support.RightClickSupport$ListPropertyAction.execute(RightClickSupport.java:182)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:491)
	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:823)
	at org.mwc.cmap.core.property_support.RightClickSupport$2.run(RightClickSupport.java:821)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)

**Comment by helenayele** [comment]
I am not reproducing the exception, but there seems still an issue.
After I set re-sample data at > None , I can't see the sensors cuts back even if I set re-sample data at > All or something in the middle like 1 sec, 5 sec, etc . Once I set the re-Sample data at > None , I see 0 cuts in the outline - [![Image from Gyazo](https://i.gyazo.com/dd77a1c4636c6ef51558c3420fd97e97.png)](https://gyazo.com/dd77a1c4636c6ef51558c3420fd97e97)
After setting resample data at > All 
[![Image from Gyazo](https://i.gyazo.com/b4d524a1e0c658a792fde9afe39ad8b5.png)](https://gyazo.com/b4d524a1e0c658a792fde9afe39ad8b5)

it still shows 0 cuts(nothing in the plot)
