### ISSUE TITLE
Thread exception on import AIS

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3467]
When we import AIS data, we have a thread related exception thrown:
````
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Display.error(Display.java:1090)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:632)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1253)
	at org.mwc.cmap.core.wizards.ImportNMEADialog.<init>(ImportNMEADialog.java:61)
	at org.mwc.debrief.core.loaders.NMEALoader$1.run(NMEALoader.java:62)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

````

This can be reproduced by the file titled `nmea.log`

Steps to reproduce:
1. Load `boat1.rep`
2. Drag in `nmea.log`

If the code is working properly, the NMEA import dialog will be shown. 

Note: the actual data-file is empty, so the plot won't change after the import.

**Comment by IanMayo** [comment]
Fixed, in #3469

**Comment by IanMayo** [comment]
Ok. I've fixed this issue, but I'm aware that we don't have test coverage for it, or for any of the AIS/NMEA import.

I'm going to create a data-file for it.  It will be a large data-file.

When we drag/drop an AIS file into Debrief, a wizard opens, that invites the user to select how frequently to sample the ownship track, and the positions of any other nearby AIS tracks.  

I wish us to have a series of RCPTT tests that ensure:
* we can drag in a file, instruct wizard to load all positions, all data loaded
* drag in a file, instruct wizard to do some sampling, check correct number of items loaded
* drag in a file, instruct wizard load no AIS entries, check zero loaded
