### ISSUE TITLE
Bug - app freeze on loading new data

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#3524]
We've got a show-stopping bug.

If we've got the Stacked Dots (bearing residuals) view open, when we open a new .rep file, the application freezes:
https://youtu.be/DY-_Ltxwyrg

@helenayele - could you verify this also happens for you?

**Comment by IanMayo** [comment]
Hmm, I've gone back to a version more than 6 months ago, and we're still getting this. Strange.

**Comment by IanMayo** [comment]
@helenayele tried to reproduce it.  She couldn't do that at first, but managed to get an NPE later on:

java.lang.NullPointerException
    at org.mwc.cmap.plotViewer.editors.CorePlotEditor.dispose(CorePlotEditor.java:620)
    at org.mwc.debrief.core.editors.PlotEditor.dispose(PlotEditor.java:1128)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:264)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:424)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)

**Comment by helenayele** [comment]
### Steps to reproduce

1. Open boat1.rep
2. Select drag track segment toolbar action to open residual view
3. select some of the toolbar actions on residual view, I selected the first 4 toolbar items on this view
4. Open boat2.rep file 
5. Open bulk_blue_tracks.rep file
6. Open bulk_red_tracks.rep file
7. Open ColorTest.rep file , select OTG mode, this time Debief goes to busy state

If you can't reproduce following this steps, try to open other rep files as well.

**Comment by helenayele** [comment]
### Other steps:
When you open the below rep files try to select OTG file format

1. Open boat1.rep
2. Select drag track segment toolbar action to open residual view
3. select some of the toolbar actions on residual view, I selected the first 4 toolbar items on this view
4. Open boat2.rep file
5. Open bulk_blue_tracks.rep file , then close it
6. Open bulk_red_tracks.rep file, then close it ,
7. Open ColorTest.rep

 This time Debrief freezes

**Comment by IanMayo** [comment]
@helenayele - I think this is fixed, would you mind trying to reproduce it, please?
