### ISSUE TITLE
D-Lite couldn't load boat_1_2_arcs.rep from sample_data

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3704]
When I  drag-and drop boat_1_2_arcs.rep to D-Lite , it logs NPE - 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mwc.debrief.lite.gui.LiteStepControl.propertyChange(LiteStepControl.java:103)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at MWC.TacticalData.temporal.TimeManager.setPeriod(TimeManager.java:154)
	at org.mwc.debrief.lite.DebriefLiteApp$4$1.run(DebriefLiteApp.java:365)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Here is the rep file
[boat_1_2_arcs.zip](https://github.com/debrief/debrief/files/2836538/boat_1_2_arcs.zip)
When I open it in Debrief , it is blank(shows nothing).
### Expected Result:
D-Lite should show blank plot instead of failing silently.

**Comment by helenayele** [comment]
This same exception is logged while trying to load formatter.rep file

**Comment by helenayele** [comment]
Exception is logged. Verified

**Comment by helenayele** [comment]
No exception is logged while loading those files and also clicking on  layers from outline view of Formatter.rep file. Hence closing..
