### ISSUE TITLE
Inserting Shapes like Rectangle, Polygon  throws NullPointerException

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3725]
When adding shapes like poly, rectangle ,etc on a plot logs Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.GenericData.WorldLocation.<init>(WorldLocation.java:123)
	at MWC.GenericData.WorldArea.<init>(WorldArea.java:71)
	at MWC.GUI.Shapes.TextLabel.getBounds(TextLabel.java:340)
	at Debrief.Wrappers.ShapeWrapper.getBounds(ShapeWrapper.java:646) ... (will attach the full log) 

###Steps to reproduce
1. Launch D-Lite
2. Drag boat1.rep to the plot
3. Insert > Click on Polygon or Rectange 
4. See that it logs the below exception, but they seem created on the outline view - [![Image from Gyazo](https://i.gyazo.com/dcaa80786ca4ac449f5f5b06ccc884be.gif)](https://gyazo.com/dcaa80786ca4ac449f5f5b06ccc884be) , but nothing is shown on the plot.
[AWT-EventQueue-0 java.lang.NullPointerException - Inserting shapes.txt](https://github.com/debrief/debrief/files/2844145/AWT-EventQueue-0.java.lang.NullPointerException.-.Inserting.shapes.txt)

**Comment by helenayele** [comment]
The same exception is logged while adding these Reference Data and click on Chart Features layer in outline view

1. CoastLine
2. Natural Earth

These is the stack trace 
[NPE_adding_ReferernceData.txt](https://github.com/debrief/debrief/files/2845465/NPE_adding_ReferernceData.txt)

**Comment by helenayele** [comment]
The above exception is not thrown when adding Coastline and Natural Earth. Currently it is thrown only when we try to insert polygon.

**Comment by helenayele** [comment]
Currently no exception is added while adding polygon. But the added polygon is doesn't have any size hence not drawn on the plot. But its label is shown on the plot and outline view. Even if I added many nodes, the shapes are not drawn.

**Comment by helenayele** [comment]
Closing per above comment.
