### ISSUE TITLE
Modifying the DTG values of Narrative entry results in Class Cast Exception

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3764]
Trying to modify both DTG Date and Time parts logs  the below exception
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: MWC.GUI.Properties.PlainPropertyEditor$PropertyChangeAction cannot be cast to java.lang.Comparable
	at java.util.concurrent.ConcurrentSkipListMap.cpr(Unknown Source)
	at java.util.concurrent.ConcurrentSkipListMap.findPredecessor(Unknown Source)
	at java.util.concurrent.ConcurrentSkipListMap.doRemove(Unknown Source)
	at java.util.concurrent.ConcurrentSkipListMap.remove(Unknown Source)
.... Full stack trace is here
[ClassCastException_NarattiveEntry.txt](https://github.com/debrief/debrief/files/2865177/ClassCastException_NarattiveEntry.txt)

### Steps to reproduce
1. Drag narrative_bulk.rep to D-Lite map
2. Expand Narratives layer and double-click the first entry 
3. Try to modify the DTG Date or Time part and press Apply.
Then the attached exception is logged and also the new entered values are not retained.

**Comment by IanMayo** [comment]
@helenayele - I've fixed this in #4133

But, there's an outstanding refresh problem with very large files. So, while it's possible to change the time of narrative entries for small narratives (<1000), they appear to freeze for very large ones.

We'll have to treat that as a separate issue. It's a lower priority issue, since D-Lite users are unlikely to work with very long narratives.

**Comment by helenayele** [comment]
The Refresh issue is handled in separate bug #4134

**Comment by helenayele** [comment]
Verified
