### ISSUE TITLE
NullPointerException while loading Rep files in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3786]
In current fix, I am getting NPE with this dialog while trying to load rep files. But the file is loaded.
[![Image from Gyazo](https://i.gyazo.com/e1b771d9b6736e7aaa6a33ec912f3872.png)](https://gyazo.com/e1b771d9b6736e7aaa6a33ec912f3872)
Full stack trace 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.Utilities.ReaderWriter.ReaderMonitor$SwingProvider$1.run(ReaderMonitor.java:159)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by ayeshare** [comment]
@helenayele Tried the same on develop now, I cant see an exception.

**Comment by helenayele** [comment]
Unable to reproduce it in this build

**Comment by helenayele** [comment]
Able to reproduce the issue in current build, and I can't open dpf file getting this thrown 
[NPE_while_opening_dpf files.txt](https://github.com/debrief/debrief/files/2910186/NPE_while_opening_dpf.files.txt)

**Comment by ayeshare** [comment]
@helenayele @IanMayo this should work after the fix for #3788 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at MWC.Utilities.ReaderWriter.ReaderMonitor$SwingProvider$1.run(ReaderMonitor.java:159)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)

This exception is not consistent. If I launch the app again and load rep file, I dont see that exception.

**Comment by helenayele** [comment]
In current build , the above exception is no more reproducible but the issue mentioned here 
 https://github.com/debrief/debrief/issues/3786#issuecomment-467837625 is still reproducible.

**Comment by ayeshare** [comment]
@IanMayo For some reason the progress monitor is null even after the check for pm!=null goes through.  I have changed the order of the calls, in the new file branch.  Still sometimes I see that progress monitor is null

**Comment by IanMayo** [comment]
@ayeshare - ooh dear, that seems like a horrible threading issue.  I think we're running threads inside threads in the import processes.

**Comment by helenayele** [comment]
Able to open rep files without any issues and also regarding dpf file separate issue https://github.com/debrief/debrief/issues/3697 is already exist. Hence closing this issue.

**Comment by ayeshare** [comment]
@IanMayo did you fix the issue?

**Comment by IanMayo** [comment]
Yes, I implemented separate `runAsync` handlers for SWT & Swing.
