### ISSUE TITLE
Need to provide dpf file extension while saving rep file

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3788]
When we save rep file in D-Lite, if we miss to give .dpf extension, the file is saved as text file even if dpf file is selected in **Files of Type** combo. like this - [![Image from Gyazo](https://i.gyazo.com/eb9d01c9ce27c203b085ced39e4982f2.png)](https://gyazo.com/eb9d01c9ce27c203b085ced39e4982f2)
If I didn't provide the .dpf after the file name, it automatically saved as text file.

**Comment by ayeshare** [comment]
@helenayele @IanMayo 
This was fixed along with other save issues

**Comment by helenayele** [comment]
@ayeshare , it works as expected while saving  rep files only. But when I try to save dpf files, the file name is empty , and if I don't provide the file extension while saving, it is saved as text file.
[![Image from Gyazo](https://i.gyazo.com/873e784960f20c28f34821b1d08a574f.gif)](https://gyazo.com/873e784960f20c28f34821b1d08a574f)

**Comment by ayeshare** [comment]
See Fix for #3790

**Comment by helenayele** [comment]
In today's fix, I get this exception whenever I try to open dpf files and the dpf file is not opened at all. Hence , I can't test this issue.

java.lang.NullPointerException
	at MWC.GUI.LayerManager.Swing.SwingLayerManager.updateData(SwingLayerManager.java:839)
	at org.mwc.debrief.lite.DebriefLiteApp.update(DebriefLiteApp.java:266)
	at org.mwc.debrief.lite.DebriefLiteApp$4.dataExtended(DebriefLiteApp.java:254)
	at MWC.GUI.Layers.fireExtended(Layers.java:983)
	at MWC.GUI.Layers.addThisLayer(Layers.java:665)
	at MWC.Utilities.ReaderWriter.XML.LayerHandler.elementClosed(LayerHandler.java:206)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReader.endElement(MWCXMLReader.java:258)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
--- full stack trace is this
[NPE_while_opening_dpf files.txt](https://github.com/debrief/debrief/files/2910084/NPE_while_opening_dpf.files.txt)

**Comment by helenayele** [comment]
Verified. Now dpf is suffixed while triggering save as action.
