### ISSUE TITLE
Provide user friendly Info when user tries to open invalid files 

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3826]
When I try to open Rep files using **Open Plot** action , it displays these dialogs in ascending order .

1. [![Image from Gyazo](https://i.gyazo.com/7c4e31bb65319acc17746379580f6fd4.png)](https://gyazo.com/7c4e31bb65319acc17746379580f6fd4)

2. [![Image from Gyazo](https://i.gyazo.com/117462fc0890310827aa902cf31d1fb2.png)](https://gyazo.com/117462fc0890310827aa902cf31d1fb2)

For some of the Rep files the first dialog may not be shown but the 2 one is common for all. 
### Expected Result:

1. No multiple error dialog should be shown for the user -  A Single error dialog should be seen
2. The file name should not be loaded in the title bar
3. Should not silently logged exception it should show the problems in dialog 
4. It would be very cool if we  provide user friendly message to our users.

**Comment by helenayele** [comment]
And also when I try to open dpf file using Import Replay action, this exception is just thrown without giving any information to the user.
Exception in thread "Thread-26" java.lang.RuntimeException: "plot" handler not found
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReader.startElement(MWCXMLReader.java:239)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReaderWriter.doImport(MWCXMLReaderWriter.java:113)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReaderWriter.importThis(MWCXMLReaderWriter.java:181)
	at Debrief.ReaderWriter.XML.DebriefXMLReaderWriter.importThis(DebriefXMLReaderWriter.java:93)
	at MWC.Utilities.ReaderWriter.ImportManager.importThisOne(ImportManager.java:405)
	at MWC.Utilities.ReaderWriter.ImportManager$importThisThread.run(ImportManager.java:343)

**Comment by helenayele** [comment]
When I open this file , I get NPE 
[boat1.zip](https://github.com/debrief/debrief/files/3098474/boat1.zip)

**Comment by helenayele** [comment]
Verified
