### ISSUE TITLE
NPE while saving a map without a track after adding shapes

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3857]
### Steps:

1. Launch D-Lite
2. Add different shapes by creating layers
3. Then when you click New, it asks you to save, then Click Okay to save.
[![Image from Gyazo](https://i.gyazo.com/ed5e3b74ea7ee242abb202458c1550dc.png)](https://gyazo.com/ed5e3b74ea7ee242abb202458c1550dc)

This time it logs NPE with the below details.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.io.File.<init>(Unknown Source)
	at org.mwc.debrief.lite.menu.DebriefRibbonFile.saveChanges(DebriefRibbonFile.java:340)
	at org.mwc.debrief.lite.menu.DebriefRibbonFile$NewFileAction.actionPerformed(DebriefRibbonFile.java:224)
	at org.pushingpixels.flamingo.api.common.AbstractCommandButton.fireActionPerformed(AbstractCommandButton.java:607)
	at org.pushingpixels.flamingo.api.common.AbstractCommandButton$ActionHandler.actionPerformed(AbstractCommandButton.java:559)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at org.pushingpixels.flamingo.api.common.model.ActionRepeatableButtonModel.setPressed(ActionRepeatableButtonModel.java:114)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonListener.mouseReleased(BasicCommandButtonListener.java:123)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by helenayele** [comment]
Verified - No NPE while saving but it doesn't provide default name , When I select Save. But it provides the default name when I select Save..as or New
[![Image from Gyazo](https://i.gyazo.com/2616c6eeb1cabe0859463635e2addddc.gif)](https://gyazo.com/2616c6eeb1cabe0859463635e2addddc)

[![Image from Gyazo](https://i.gyazo.com/1e7c486b0bfc61863251ee99c559da81.gif)](https://gyazo.com/1e7c486b0bfc61863251ee99c559da81)

**Comment by IanMayo** [comment]
Re-open, since we don't provided default for nameless plot.

**Comment by helenayele** [comment]
Verified
