### ISSUE TITLE
Unable to load rep and dpf file in D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#3967]
When I try to load rep and dpf files, I get NPE thrown and the positions are not loaded in Debrief.
[![Image from Gyazo](https://i.gyazo.com/9e17ce2e98c95f57b80d26abd6afd34f.png)](https://gyazo.com/9e17ce2e98c95f57b80d26abd6afd34f) 
And this is logged
Exception in thread "Thread-13" java.lang.NullPointerException
	at org.mwc.debrief.lite.DebriefLiteApp$1.propertyChange(DebriefLiteApp.java:141)
	at org.mwc.debrief.lite.DebriefLiteApp.notifyListenersStateChanged(DebriefLiteApp.java:150)
	at org.mwc.debrief.lite.DebriefLiteApp.setState(DebriefLiteApp.java:128)
	at org.mwc.debrief.lite.DebriefLiteApp$6.dataExtended(DebriefLiteApp.java:398)
	at MWC.GUI.Layers.fireExtended(Layers.java:983)
	at MWC.GUI.Layers.addThisLayer(Layers.java:665)
	at MWC.Utilities.ReaderWriter.PlainImporterBase.addLayer(PlainImporterBase.java:168)
	at Debrief.ReaderWriter.Replay.ImportReplay.processReplayFix(ImportReplay.java:2133)
	at Debrief.ReaderWriter.Replay.ImportReplay.readLine(ImportReplay.java:2331)
	at Debrief.ReaderWriter.Replay.ImportReplay.importRep(ImportReplay.java:1630)
	at Debrief.ReaderWriter.Replay.ImportReplay.importThis(ImportReplay.java:1568)
	at MWC.Utilities.ReaderWriter.PlainImporterBase.importThis(PlainImporterBase.java:134)
	at MWC.Utilities.ReaderWriter.ImportManager.importThisOne(ImportManager.java:405)
	at MWC.Utilities.ReaderWriter.ImportManager$importThisThread.run(ImportManager.java:343)
And Dpf files are also behaving the same. For example when I try to load 'CompositeTrack.dpf' file I get this loaded - [![Image from Gyazo](https://i.gyazo.com/801b6fcc2ab49136edc6eef91ae2c2ab.png)](https://gyazo.com/801b6fcc2ab49136edc6eef91ae2c2ab)

And it throws 
[NPE While loading_dpf.txt](https://github.com/debrief/debrief/files/3046663/NPE.While.loading_dpf.txt)

**Comment by helenayele** [comment]
Verified
