### ISSUE TITLE
Outline toolbar buttons will be enabled after undo/redo actions

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4125]
During undo and redo actions buttons like
1. Edit
2. Cut
3. Copy
4. Delete buttons 
are enabled without any layer/item selection in the outline pane and if we select them, they will throw the following exceptions:
[![Image from Gyazo](https://i.gyazo.com/20c770e17f662077d76b1fabc2e2d787.png)](https://gyazo.com/20c770e17f662077d76b1fabc2e2d787)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mwc.debrief.lite.outline.OutlinePanelView.editThis(OutlinePanelView.java:616)
	at org.mwc.debrief.lite.outline.OutlinePanelView$10.actionPerformed(OutlinePanelView.java:848)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:108)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)...

**Comment by helenayele** [comment]
Verified
