### ISSUE TITLE
Hide/Disable inappropriate XY Graphs

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4143]
Currently when we open a file with single track, we show all the graphs available in the system. And when user chooses a graph that needs 2 tracks , we show empty graph. It would be good if we don't show those graph that needs 2 tracks if user opens a file with single track.
[![Image from Gyazo](https://i.gyazo.com/afc05dcb26fa8cb1f1bc31e952caccaa.png)](https://gyazo.com/afc05dcb26fa8cb1f1bc31e952caccaa)

### Steps:
1. Open boat1.rep
2. Open XY graph and select Range
3. See that it only contain Nelson track and yet Range , bearning and other graphs are enabled.
4. Select Range and see that no graph is shown, but all the graph toolbar buttons are enabled. Try to select each of them like this :

[![Image from Gyazo](https://i.gyazo.com/2177345edd055cee4de06cf029f87aaf.gif)](https://gyazo.com/2177345edd055cee4de06cf029f87aaf)

And selecting 'Copies the graph as a text matrix..' actions throws NPE :
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.Utilities.XYPlot.XYPlotUtilities.textMatrix(XYPlotUtilities.java:49)
	at MWC.Utilities.XYPlot.XYPlotUtilities.copyToClipboard(XYPlotUtilities.java:40)
	at org.mwc.debrief.lite.graph.GraphPanelToolbar$10.actionPerformed(GraphPanelToolbar.java:398)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)....

**Comment by helenayele** [comment]
Able to hide inappropriate xy graphs now - Verified
