### ISSUE TITLE
Trouble loading D-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4297]
A developer who is supporting us in GeoTools usage is having trouble staring Debrief.

I don't think the `SplashScreen` problem is real, since I think I also get it. Plus, the splash screen isn't related to Flamingo.

The "resize policies" issue is discussed in this article:
https://blog.frankel.ch/flamingo-tutorial/

````
SplashScreen.getSplashScreen() returned null
Path for splash screen image should be provided in command path: -splash:src/main/java/images/splash.gif
Exception in thread "AWT-EventQueue-1" java.lang.IllegalStateException: Inconsistent preferred widths
Ribbon band 'Export' has the following resize policies
org.pushingpixels.flamingo.api.ribbon.resize.CoreRibbonResizePolicies$Mirror with preferred width 48
org.pushingpixels.flamingo.api.ribbon.resize.CoreRibbonResizePolicies$IconRibbonBandResizePolicy with preferred width 56
org.pushingpixels.flamingo.api.ribbon.resize.CoreRibbonResizePolicies$Mirror with pref width 48 is followed by resize policy org.pushingpixels.flamingo.api.ribbon.resize.CoreRibbonResizePolicies$IconRibbonBandResizePolicy with larger pref width

at org.pushingpixels.flamingo.internal.utils.FlamingoUtilities.checkResizePoliciesConsistency(FlamingoUtilities.java:113)
at org.pushingpixels.flamingo.api.ribbon.AbstractRibbonBand.setRibbonTask(AbstractRibbonBand.java:499)
at org.pushingpixels.flamingo.api.ribbon.RibbonTask.<init>(RibbonTask.java:89)
at org.mwc.debrief.lite.menu.DebriefRibbonFile.addFileTab(DebriefRibbonFile.java:382)
at org.mwc.debrief.lite.menu.DebriefRibbon.<init>(DebriefRibbon.java:46)
at org.mwc.debrief.lite.DebriefLiteApp.createAppPanels(DebriefLiteApp.java:748)
at org.mwc.debrief.lite.DebriefLiteApp.<init>(DebriefLiteApp.java:657)
at org.mwc.debrief.lite.DebriefLiteApp$3.run(DebriefLiteApp.java:286)
````

**Comment by IanMayo** [comment]
Hmm, I've just opened the app on my MacBook. The icons all seem smaller.  I'm in branch `4280_handle_tif`

This is what I get:
![image](https://user-images.githubusercontent.com/1108513/60122403-090c0680-977d-11e9-9797-461d7dddc45c.png)

**Comment by ayeshare** [comment]
The icons are not smaller on windows.  It looks the same even with the new policy

**Comment by IanMayo** [comment]
New policy fixed it.
