### ISSUE TITLE
D-Lite performance with long snail trails.

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4394]
I loaded some client tracks, and Snail trails were really slow - you could almost see them being drawn.

Our demo tracks are fine (`boat1.rep` and `boat2.rep`). But, that's because the trails are short.  If we extend Snail Trail Length to 2 hours, we get the problem.

Change snail length by clicking the Properties button to the left of the time control.  Then click on the `Edit display mode` button. If you're in Snail mode - you get the snail mode options.

Setting the trail length to 4 hours makes the performance drop.

**Comment by IanMayo** [comment]
@helenayele - could you see if you have the above problem? 

It don't have it on my Mac.

**Comment by helenayele** [comment]
I don't have it in my window either
https://screencast-o-matic.com/watch/cqilIqObaA

**Comment by IanMayo** [comment]
@helenayele  - how about if you drag the time slider when in snail mode?

**Comment by helenayele** [comment]
When I slide it , it throws the below NPE. 
but I don't see that much difference in its performance 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.awt.Point.<init>(Unknown Source)
	at Debrief.GUI.Tote.Painters.SnailDrawFix2.drawMe(SnailDrawFix2.java:267)
	at Debrief.GUI.Tote.Painters.SnailPainter2.highlightIt(SnailPainter2.java:273)
	at Debrief.GUI.Tote.Painters.SnailPainter2.newTime(SnailPainter2.java:398)
	at Debrief.GUI.Tote.Painters.TotePainter.paintMe(TotePainter.java:417)
	at org.mwc.debrief.lite.DebriefLiteApp.redoTimePainter(DebriefLiteApp.java:1416)
	at org.mwc.debrief.lite.DebriefLiteApp.doPaint(DebriefLiteApp.java:1025)
	at org.mwc.debrief.lite.DebriefLiteApp$16.paint(DebriefLiteApp.java:1372)
	at org.mwc.debrief.lite.map.GeoToolMapRenderer.paintEvent(GeoToolMapRenderer.java:139)
	at org.mwc.debrief.lite.map.LiteMapPane.paintComponent(LiteMapPane.java:198)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by IanMayo** [comment]
Re-open, still poor performance on screens with very high res
