### ISSUE TITLE
NPE while opening offset_times.rep file

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4444]
While loading 'offset_times.rep' from sample-data project, D-Lite throws Null pointer Exception with the below stack traces:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl$somePeriod.extend(StepControl.java:1223)
	at Debrief.GUI.Tote.StepControl.recalcTimes(StepControl.java:972)
	at Debrief.GUI.Tote.StepControl.addParticipant(StepControl.java:905)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:445)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:119)
	at Debrief.GUI.Tote.AnalysisTote.setPrimary(AnalysisTote.java:409)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:85)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:119)
	at Debrief.GUI.Tote.AnalysisTote.dataReformatted(AnalysisTote.java:772)
	at MWC.GUI.Layers.fireReformatted(Layers.java:1044)
	at org.mwc.debrief.lite.DebriefLiteApp$3.performOperation(DebriefLiteApp.java:668)
	at MWC.TacticalData.temporal.PlotOperations.performOperation(PlotOperations.java:162)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$SliderListener.stateChanged(DebriefRibbonTimeController.java:279)
	at javax.swing.JSlider.fireStateChanged(Unknown Source)
	at javax.swing.JSlider$ModelListener.stateChanged(Unknown Source)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(Unknown Source)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(Unknown Source)
	at javax.swing.DefaultBoundedRangeModel.setMinimum(Unknown Source)
	at javax.swing.JSlider.setMinimum(Unknown Source)
	at org.mwc.debrief.lite.gui.custom.RangeSlider.setMinimum(RangeSlider.java:112)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$LiteSliderControls.setToolboxStartTime(DebriefRibbonTimeController.java:178)
	at org.mwc.debrief.lite.gui.LiteStepControl.propertyChange(LiteStepControl.java:191)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at MWC.TacticalData.temporal.TimeManager.setPeriod(TimeManager.java:164)
	at org.mwc.debrief.lite.DebriefLiteApp$15$1.run(DebriefLiteApp.java:1369)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

But the same file is opened by full debrief without any issues.
[![Image from Gyazo](https://i.gyazo.com/2cd55b44685de36fe548175f01ac2723.png)](https://gyazo.com/2cd55b44685de36fe548175f01ac2723)

**Comment by IanMayo** [comment]
@helenayele - at the end of `offset_times.rep` are a bunch of random unusual entries. Could you try deleting some/all of them, and seeing if the problem still occurs?

You may be able to help @saulhidalgoaular by narrowing the problem down to a specific data type.

Or, if you delete all of them, and we know it's still failing, then we know it's in the track data.

**Comment by helenayele** [comment]
Yes, when I remove the TEXT entries at the end of the file , I get the file opened - 
[![Image from Gyazo](https://i.gyazo.com/1d112ed978384339d25730351aa82c72.png)](https://gyazo.com/1d112ed978384339d25730351aa82c72)
I removed the below lines :

;TEXT: 0B[LAYER=Buoys] 22.15 0 0 N 21.6 0 0 W Active buoy 
;TEXT: 1C[LAYER=Buoys] 22.2 0 0 N 21.6 0 0 W Difar buoy 
;TEXT: 2D[LAYER=Buoys] 22.25 0 0 N 21.6 0 0 W Lofar buoy

**Comment by IanMayo** [comment]
Hey, good investigating @helenayele 

What if it's a `.rep` file containing just that line?

(I'm trying to determine the minimum file necessary to trigger the problem).

**Comment by IanMayo** [comment]
Oh dear @helenayele - `offset_times.rep` opens ok for me.  That suggests it may be timezone related.

But, from looking at the bug-listing, it's because some item in the *Outline* is returning an empty Time Period.  We could just check that sp is non-null before using it (at line #967 of StepControl).  But, it would be much more useful to learn about which element is returning a null TimePeriod - that may be a sign of some issue.

**Comment by helenayele** [comment]
When I move those cut TEXT Lines on boat1.rep file, I can open it without any issues:
[![Image from Gyazo](https://i.gyazo.com/f1d1361f0ce9d889a5ef19683972fb56.png)](https://gyazo.com/f1d1361f0ce9d889a5ef19683972fb56)

**Comment by helenayele** [comment]
Able to open `offset_times.rep` file without any issue in develop branch now

**Comment by helenayele** [comment]
Verified
