### ISSUE TITLE
Undo and Redo issues while removing track

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4450]
After I delete tracks from the outline panel, I am not able to retrieve the deleted tracks using undo/redo functionality.

### Steps :
1. Launch D-Lite
2. Open BULK_BLUE_TRACKS.rep
3. Delete the first T23..tracks - see that undo button is enabled - this is fine
4. Delete HVU track ---see that the redo button now gets enabled - this button should not be enabled since we didn't select undo button
5. Delete the remaining T23A track
6. Now select Undo button , see that only the last removed  T23A track is retrieved by this action
https://screencast-o-matic.com/watch/cqj6eNOPlA

Note :
This issue is not reproducible with shapes though.

**Comment by helenayele** [comment]
Currently I can retrieve it the deleted track using undo action. But if there were graphs drawn , selecting undo action doesn't retrieve the graphs that were drawn, but the toolbar buttons are kept enabled. 
[![Image from Gyazo](https://i.gyazo.com/b00c5a25a0026b4eaaab5dd635fd1249.png)](https://gyazo.com/b00c5a25a0026b4eaaab5dd635fd1249)
And also see that the select tracks combo has the tracks name being selected.
And all the graphs toolbar menus are enabled and selecting 'Copies the graphs as text matrix..' button throws this NPE

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.Utilities.XYPlot.XYPlotUtilities.textMatrix(XYPlotUtilities.java:49)
	at MWC.Utilities.XYPlot.XYPlotUtilities.copyToClipboard(XYPlotUtilities.java:40)
	at org.mwc.debrief.lite.gui.custom.graph.GraphPanelToolbar$11.actionPerformed(GraphPanelToolbar.java:477)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:108)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by helenayele** [comment]
Verified
