### ISSUE TITLE
Time controller menus should be disabled when only shapes exist on map panel

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4451]
Currently when I add any of the shapes from insert menu , time controls are enabled and even play button resumes playing even if it shows nothing in time slider and filter to time controls.

We need to keep disabled all time controls as long as no track is present in map panel.
[![Image from Gyazo](https://i.gyazo.com/2ce1b3598c8559b794f972b77a261c31.gif)](https://gyazo.com/2ce1b3598c8559b794f972b77a261c31)

### Steps :
1. Launch D-Lite
2. Insert Circle
3. Open Time menu and select Play button
4. When you select play it throws the below exception continuously
INFO:  Exception caught:null
java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl.validTime(StepControl.java:579)
	at Debrief.GUI.Tote.StepControl.doStep(StepControl.java:540)
	at Debrief.GUI.Tote.StepControl.onTime(StepControl.java:1081)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)
INFO:  Exception caught:null
java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl.validTime(StepControl.java:579)
	at Debrief.GUI.Tote.StepControl.doStep(StepControl.java:540)
	at Debrief.GUI.Tote.StepControl.onTime(StepControl.java:1081)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)
INFO:  Exception caught:null
java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl.validTime(StepControl.java:579)
	at Debrief.GUI.Tote.StepControl.doStep(StepControl.java:540)
	at Debrief.GUI.Tote.StepControl.onTime(StepControl.java:1081)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)
INFO:  Exception caught:null
java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl.validTime(StepControl.java:579)
	at Debrief.GUI.Tote.StepControl.doStep(StepControl.java:540)
	at Debrief.GUI.Tote.StepControl.onTime(StepControl.java:1081)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)
INFO:  Exception caught:null
java.lang.NullPointerException
	at Debrief.GUI.Tote.StepControl.validTime(StepControl.java:579)
	at Debrief.GUI.Tote.StepControl.doStep(StepControl.java:540)
	at Debrief.GUI.Tote.StepControl.onTime(StepControl.java:1081)
	at MWC.Utilities.Timer.Timer.fireTimerEvent(Timer.java:141)
	at MWC.Utilities.Timer.Timer$TimerThread.run(Timer.java:163)....................

**Comment by helenayele** [comment]
After deleting all tracks in the outline panel, still Time control menus are active, and resumes playing as if tracks exist in the map panel
### Steps to reproduce:
1. Launch D-Lite
2. Open boat1.rep
3. Open Time menu and select Play
4. Delete the Nelson Track from outline panel
5. See that the player stops playing and all time controller menus are active
6. Select Play button 
See that is resumes playing as if track is present 

[![Image from Gyazo](https://i.gyazo.com/5335ab748cd6f0aacc61f1a9a1243127.gif)](https://gyazo.com/5335ab748cd6f0aacc61f1a9a1243127)

**Comment by helenayele** [comment]
Due to the above issue, re-opening...

**Comment by helenayele** [comment]
Verified
