### ISSUE TITLE
NPE when importing shapes.rep

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4457]
Somehow I am getting NPE while importing `shapes.rep`. Here is the log.

Path for splash screen image should be provided in command path: -splash:src/main/java/images/splash.gif
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at MWC.GenericData.HiResDate.greaterThan(HiResDate.java:223)
	at Debrief.GUI.Tote.StepControl$somePeriod.extend(StepControl.java:1223)
	at Debrief.GUI.Tote.StepControl.recalcTimes(StepControl.java:972)
	at Debrief.GUI.Tote.StepControl.addParticipant(StepControl.java:905)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:445)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setSecondary(AnalysisTote.java:449)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:95)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.setPrimary(AnalysisTote.java:409)
	at org.mwc.debrief.lite.LiteTote.addItem(LiteTote.java:85)
	at org.mwc.debrief.lite.LiteTote.updateToteMembers(LiteTote.java:132)
	at Debrief.GUI.Tote.AnalysisTote.dataReformatted(AnalysisTote.java:772)
	at MWC.GUI.Layers.fireReformatted(Layers.java:1044)
	at org.mwc.debrief.lite.DebriefLiteApp$3.performOperation(DebriefLiteApp.java:668)
	at MWC.TacticalData.temporal.PlotOperations.performOperation(PlotOperations.java:162)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$SliderListener.stateChanged(DebriefRibbonTimeController.java:279)
	at javax.swing.JSlider.fireStateChanged(JSlider.java:432)
	at javax.swing.JSlider$ModelListener.stateChanged(JSlider.java:350)
	at javax.swing.DefaultBoundedRangeModel.fireStateChanged(DefaultBoundedRangeModel.java:364)
	at javax.swing.DefaultBoundedRangeModel.setRangeProperties(DefaultBoundedRangeModel.java:302)
	at javax.swing.DefaultBoundedRangeModel.setMinimum(DefaultBoundedRangeModel.java:203)
	at javax.swing.JSlider.setMinimum(JSlider.java:578)
	at org.mwc.debrief.lite.gui.custom.RangeSlider.setMinimum(RangeSlider.java:112)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$LiteSliderControls.setToolboxStartTime(DebriefRibbonTimeController.java:178)
	at org.mwc.debrief.lite.gui.LiteStepControl.propertyChange(LiteStepControl.java:191)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at MWC.TacticalData.temporal.TimeManager.setPeriod(TimeManager.java:164)
	at org.mwc.debrief.lite.DebriefLiteApp$15$1.run(DebriefLiteApp.java:1369)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by saulhidalgoaular** [comment]
It was working properly on 89cdd9348aac5b8ba47bbed85ca74091964327ae

**Comment by IanMayo** [comment]
May be related to #4444 

The error stack looks similar.

**Comment by helenayele** [comment]
Verified no issue while opening `shapes.rep`, `shape.dpf ` and `offset_times.rep` files without any issues.
