### ISSUE TITLE
Light weight tracks' marker are not hidden when the tracks become invisible

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4459]
In Normal mode, when I turned off the visibility of the light weight track, the markers are not hidden,
Issue :
[![Image from Gyazo](https://i.gyazo.com/ee4a99d53d92f6b2ff3cb2f948b49b05.gif)](https://gyazo.com/ee4a99d53d92f6b2ff3cb2f948b49b05)
### Steps to reproduce:
1. Load BULK_RED_TRACKS.rep file
2. In Time menu, Select Normal display mode
3. In outline panel, select Red_forces(3000 items) layer and select the eye icon to turn off the visibility of the the track positions
4. See that all the positions are hidden but the markers stays visible
Note:
This is not happening in normal tracks like boat1.rep or boat2.dpf
5. Select New and load boat2.rep file , select Normal display mode
6. Select the eye icon on the COOLINGWOOD LAYER to make it invisble
Note that no marker is visible
7. Select New - don't save the boat2 file
8. Load again BULK_RED_TRACKS.rep file 
This time the below NPE is logged 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at Debrief.Wrappers.Track.LightweightTrackWrapper.getNearestTo(LightweightTrackWrapper.java:737)
	at Debrief.GUI.Tote.Painters.TotePainter.newTime(TotePainter.java:514)
	at Debrief.GUI.Tote.Painters.PainterManager.newTime(PainterManager.java:171)
	at org.mwc.debrief.lite.DebriefLiteApp.redoTimePainter(DebriefLiteApp.java:1513)
	at org.mwc.debrief.lite.DebriefLiteApp.access$8(DebriefLiteApp.java:1469)
	at org.mwc.debrief.lite.DebriefLiteApp$11.run(DebriefLiteApp.java:917)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)...
Full stack trace 
[java.lang.NullPointerException_normal_mode_lighweight_Tracks.txt](https://github.com/debrief/debrief/files/3491198/java.lang.NullPointerException_normal_mode_lighweight_Tracks.txt)

After this exception is logged, I try to switch to Snail mode, but I can't switch back to Normal mode.

**Comment by helenayele** [comment]
Verified
