### ISSUE TITLE
Issues while opening compositeTrack file

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4461]
When I open 'compositeTrack.dpf' file from old Debrief version's sample_data folder, I get the below error dialog:
[![Image from Gyazo](https://i.gyazo.com/3a7c6cc854ff49889388f9c076716b32.gif)](https://gyazo.com/3a7c6cc854ff49889388f9c076716b32)
The file is this 
[compositeTrack.zip](https://github.com/debrief/debrief/files/3495678/compositeTrack.zip)

And this is logged 
 java.lang.ClassCastException: Debrief.GUI.Tote.Painters.SnailPainter2 cannot be cast to Debrief.GUI.Tote.Painters.SnailPainter
	at Debrief.ReaderWriter.XML.GUI.StepperHandler.makeThis(StepperHandler.java:64)
	at Debrief.ReaderWriter.XML.GUIHandler.addThisComponent(GUIHandler.java:97)
	at Debrief.ReaderWriter.XML.GUIHandler$1.addComponent(GUIHandler.java:66)
	at Debrief.ReaderWriter.XML.GUI.ComponentHandler.elementClosed(ComponentHandler.java:59)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReader.endElement(MWCXMLReader.java:259)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReaderWriter.doImport(MWCXMLReaderWriter.java:170)
	at MWC.Utilities.ReaderWriter.XML.MWCXMLReaderWriter.importThis(MWCXMLReaderWriter.java:333)
	at Debrief.ReaderWriter.XML.DebriefXMLReaderWriter.importThis(DebriefXMLReaderWriter.java:121)
	at org.mwc.debrief.lite.DebriefLiteApp.handleImportDPF(DebriefLiteApp.java:1240)
	at org.mwc.debrief.lite.DebriefLiteApp.FilesReceived(DebriefLiteApp.java:1198)
	at MWC.GUI.DragDrop.FileDropSupport.fileReceived(FileDropSupport.java:145)
	at MWC.GUI.DragDrop.FileDropSupport.drop(FileDropSupport.java:179)
	at java.awt.dnd.DropTarget.drop(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by helenayele** [comment]
Verified - opened without any issues :
[![Image from Gyazo](https://i.gyazo.com/8d72f76ffe4fdecd434e7d3b1f8a45d4.gif)](https://gyazo.com/8d72f76ffe4fdecd434e7d3b1f8a45d4)
