### ISSUE TITLE
Drag Whole Features fails to work in full debrief

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4481]
When Selecting 'Drag Whole Features' toolbar item and hovering on the tracks/shapes, the log is flooded with Unhandled event loop exception exception.
java.lang.NullPointerException
	at MWC.GUI.Shapes.PolygonShape.rangeFrom(PolygonShape.java:646)
	at MWC.GUI.Shapes.PlainShape.findNearestHotSpotIn(PlainShape.java:319)
	at Debrief.Wrappers.ShapeWrapper.findNearestHotSpotIn(ShapeWrapper.java:486)
	at MWC.GUI.Shapes.FindNearest.findNearest(FindNearest.java:110)
	at MWC.GUI.Shapes.FindNearest.findNearest(FindNearest.java:132)
	at org.mwc.debrief.core.actions.DragFeature.findNearest(DragFeature.java:637)
	at org.mwc.debrief.core.actions.DragFeature$DragFeatureMode.doMouseMove(DragFeature.java:327)
	at org.mwc.cmap.plotViewer.editors.chart.SWTChart.doMouseMove(SWTChart.java:893)
	at org.mwc.cmap.plotViewer.editors.chart.SWTChart$2.mouseMove(SWTChart.java:626)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:216)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.views.log.EventDetailsDialog.open(EventDetailsDialog.java:191)
	at org.eclipse.ui.internal.views.log.EventDetailsDialogAction.run(EventDetailsDialogAction.java:102)
	at org.eclipse.ui.internal.views.log.LogView.lambda$2(LogView.java:565)
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:776)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:773)
	at org.eclipse.jface.viewers.AbstractTreeViewer.handleDoubleSelect(AbstractTreeViewer.java:1516)
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1203)
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:251)
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:308)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by IanMayo** [comment]
Hrey @helenayele  - this is a big one.  Does it happen for all shapes, or just for polygons?

**Comment by helenayele** [comment]
Yes, it happens only for polygon, it works for all the other shapes like ellipses, arcs, circle,etc

**Comment by IanMayo** [comment]
Aah, this may be sensitive to the plot being looked at. Do you remember which plot you had open @helenayele ?

**Comment by helenayele** [comment]
Yes, I remember it was sen_tracks.rep file

**Comment by helenayele** [comment]
hmm, the thing is I can reproduce on the previous version of full debrief as well.
[![Image from Gyazo](https://i.gyazo.com/0255f7732ca9f01c81acbd429c95413b.gif)](https://gyazo.com/0255f7732ca9f01c81acbd429c95413b)

**Comment by IanMayo** [comment]
I suspect it goes back years :-(

**Comment by helenayele** [comment]
Verified
