### ISSUE TITLE
Bunch of errors while resizing D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4576]
While resizing D-Lite, after some time , a bunch of errors are logged continuously.
Errors:
[![Image from Gyazo](https://i.gyazo.com/c046da3c3775bac178d30ce7f19dddb9.png)](https://gyazo.com/c046da3c3775bac178d30ce7f19dddb9)
Please see this video:
https://screencast-o-matic.com/watch/cq6j26urmm

**Comment by saulhidalgoaular** [comment]
Good afternoon @helenayele . I assume this happens when the view is too zoomed out. Could you confirm that?
My approach would be to force Debrief Lite to have a minimum zoom, and even after resizing, it doesn't zoom out more.

**Comment by helenayele** [comment]
@saulhidalgoaular ,  I get those exceptions when the view is too zoomed-In.

https://screencast-o-matic.com/watch/cq6riwupBo

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mwc.debrief.lite.gui.GeoToolMapProjection.toScreen(GeoToolMapProjection.java:147)
	at Debrief.GUI.Tote.Painters.Highlighters.PlotHighlighter$RectangleHighlight.highlightIt(PlotHighlighter.java:192)
	at Debrief.GUI.Tote.Painters.TotePainter.createNewHighlights(TotePainter.java:600)
	at Debrief.GUI.Tote.Painters.TotePainter.newTime(TotePainter.java:909)
	at Debrief.GUI.Tote.Painters.TotePainter.paintMe(TotePainter.java:934)
	at org.mwc.debrief.lite.DebriefLiteApp.redoTimePainter(DebriefLiteApp.java:1527)
	at org.mwc.debrief.lite.DebriefLiteApp.doPaint(DebriefLiteApp.java:1108)
	at org.mwc.debrief.lite.DebriefLiteApp$17.paint(DebriefLiteApp.java:1476)
	at org.mwc.debrief.lite.map.GeoToolMapRenderer.paintEvent(GeoToolMapRenderer.java:139)
	at org.mwc.debrief.lite.map.LiteMapPane.paintComponent(LiteMapPane.java:240)
	at javax.swing.JComponent.paint(Unknown Source)
	at org.mwc.debrief.lite.map.LiteMapPane.paint(LiteMapPane.java:195)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by helenayele** [comment]
hmm, I am now getting different error while resizing than this logged one :
https://screencast-o-matic.com/watch/cqXojnUYYc

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at Debrief.GUI.Tote.Painters.Highlighters.PlotHighlighter$RectangleHighlight.highlightIt(PlotHighlighter.java:194)
	at Debrief.GUI.Tote.Painters.TotePainter.createNewHighlights(TotePainter.java:601)
	at Debrief.GUI.Tote.Painters.TotePainter.newTime(TotePainter.java:910)
	at Debrief.GUI.Tote.Painters.TotePainter.paintMe(TotePainter.java:935)
	at org.mwc.debrief.lite.DebriefLiteApp.redoTimePainter(DebriefLiteApp.java:1602)
	at org.mwc.debrief.lite.DebriefLiteApp.doPaint(DebriefLiteApp.java:1160)
	at org.mwc.debrief.lite.DebriefLiteApp$17.paint(DebriefLiteApp.java:1551)
	at org.mwc.debrief.lite.map.GeoToolMapRenderer.paintEvent(GeoToolMapRenderer.java:139)
	at org.mwc.debrief.lite.map.LiteMapPane.paintComponent(LiteMapPane.java:318)
	at javax.swing.JComponent.paint(Unknown Source)
	at org.mwc.debrief.lite.map.LiteMapPane.paint(LiteMapPane.java:273)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source

Shall I file it as separate issue?

**Comment by IanMayo** [comment]
Yes please @helenayele  - new issue.  Well spotted :-D

**Comment by helenayele** [comment]
Okay filed at #4658.
