### ISSUE TITLE
Export Track to GPX ctx menu doesn't work on Java11

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4606]
Trying to invoke `Export Track to GPX `ctx menu doesn't work and throws NPE .

[![Image from Gyazo](https://i.gyazo.com/c03febb90d2e7f801cdb8f4a5170e20f.gif)](https://gyazo.com/c03febb90d2e7f801cdb8f4a5170e20f)

Stack trace:
java.lang.NoClassDefFoundError: Could not initialize class org.mwc.debrief.core.loaders.JaxbGpxHelper
	at org.mwc.debrief.core.gpx.ImportGPX.doExport(ImportGPX.java:48)
	at org.mwc.debrief.core.operations.ExportTrackToGPX$ExportTrack.execute(ExportTrackToGPX.java:141)
	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:829)
	at org.mwc.debrief.core.operations.ExportTrackToGPX.runIt(ExportTrackToGPX.java:100)
	at org.mwc.debrief.core.operations.ExportTrackToGPX$1.run(ExportTrackToGPX.java:79)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by helenayele** [comment]
But it works in Debrief 
Version: 3.0.494
Build id: 20191025
Build date: 2019-10-25
[![Image from Gyazo](https://i.gyazo.com/4e4e1d1d9402b7bae0fe2ee666e94da8.gif)](https://gyazo.com/4e4e1d1d9402b7bae0fe2ee666e94da8)

**Comment by IanMayo** [comment]
Great, thanks for investigating @helenayele

**Comment by IanMayo** [comment]
@theanuradha - this looks like a J11 import/dependency issue - jaxb seems missing.

Could you look into it please?

**Comment by helenayele** [comment]
It correctly exports to GPX file so closing..
[![Image from Gyazo](https://i.gyazo.com/07547bd9e49e586c3659c653e61b9879.gif)](https://gyazo.com/07547bd9e49e586c3659c653e61b9879)
