### ISSUE TITLE
ExecutionException is thrown while making lightweight tracks secondary

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4614]
After I make lightweight tracks primary, when I try to make other lightweight tracks as secondary I get 
org.eclipse.core.commands.ExecutionException thrown on the log. But the track is assigned as secondary track.
### Steps to reproduce:
1. Load Lightweight_Test_Tracks.rep
2. Expand red_tracks layer
3. Right click the first track (Fisherone_002) > Make Primary
4. Right click the second track (Fishertwo_003) > Make Secondary
This time it logs the below exception 
Note:
This issue is reproducible in the previous releases of Debrief Version: 3.0.494 Build id: 20191025

#### StackTrace
org.eclipse.core.commands.ExecutionException: While executing the operation, an exception occurred
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:503)
	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:825)
	at org.mwc.debrief.core.editors.PlotOutlinePage$21.run(PlotOutlinePage.java:1583)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
Caused by: java.lang.ClassCastException: Debrief.Wrappers.Track.LightweightTrackWrapper cannot be cast to Debrief.Wrappers.ISecondaryTrack
	at org.mwc.debrief.track_shift.views.BaseStackedDotsView.getTargetZones(BaseStackedDotsView.java:2479)
	at org.mwc.debrief.track_shift.views.BaseStackedDotsView.updateTargetZones(BaseStackedDotsView.java:3554)
	at org.mwc.debrief.track_shift.views.BaseStackedDotsView.access$8(BaseStackedDotsView.java:3543)
	at org.mwc.debrief.track_shift.views.BaseStackedDotsView$3.tracksUpdated(BaseStackedDotsView.java:664)
	at org.mwc.cmap.core.DataTypes.TrackData.TrackManager.setPrimaryImpl(TrackManager.java:567)
	at org.mwc.cmap.core.DataTypes.TrackData.TrackManager.setPrimary(TrackManager.java:546)
	at org.mwc.debrief.core.editors.PlotOutlinePage$21$1.doItTo(PlotOutlinePage.java:1546)
	at org.mwc.debrief.core.editors.PlotOutlinePage.applyOperation(PlotOutlinePage.java:379)
	at org.mwc.debrief.core.editors.PlotOutlinePage$SelectionOperation.execute(PlotOutlinePage.java:287)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:495)

**Comment by helenayele** [comment]
Verified
