### ISSUE TITLE
NullPointerException while resizing D-Lite

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4658]
While resizing D-Lite, a lot  of NPE are thrown on the log. 
Please see the video 
https://screencast-o-matic.com/watch/cqXojnUYYc

StackTrace:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at Debrief.GUI.Tote.Painters.Highlighters.PlotHighlighter$RectangleHighlight.highlightIt(PlotHighlighter.java:194)
at Debrief.GUI.Tote.Painters.TotePainter.createNewHighlights(TotePainter.java:601)
at Debrief.GUI.Tote.Painters.TotePainter.newTime(TotePainter.java:910)
at Debrief.GUI.Tote.Painters.TotePainter.paintMe(TotePainter.java:935)
at org.mwc.debrief.lite.DebriefLiteApp.redoTimePainter(DebriefLiteApp.java:1602)
at org.mwc.debrief.lite.DebriefLiteApp.doPaint(DebriefLiteApp.java:1160)
at org.mwc.debrief.lite.DebriefLiteApp$17.paint(DebriefLiteApp.java:1551)
at org.mwc.debrief.lite.map.GeoToolMapRenderer.paintEvent(GeoToolMapRenderer.java:139)
at org.mwc.debrief.lite.map.LiteMapPane.paintComponent(LiteMapPane.java:318)
at javax.swing.JComponent.paint(Unknown Source)
at org.mwc.debrief.lite.map.LiteMapPane.paint(LiteMapPane.java:273)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at javax.swing.JLayeredPane.paint(Unknown Source)
at javax.swing.JComponent.paintChildren(Unknown Source)
at javax.swing.JComponent.paintToOffscreen(Unknown Source)
at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
at javax.swing.RepaintManager.paint(Unknown Source)
at javax.swing.JComponent.paint(Unknown Source)
at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
at java.awt.Container.paint(Unknown Source)
at java.awt.Window.paint(Unknown Source)
at javax.swing.RepaintManager$4.run(Unknown Source)
at javax.swing.RepaintManager$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
at javax.swing.RepaintManager.access$1200(Unknown Source)
at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source

**Comment by helenayele** [comment]
Verified

**Comment by helenayele** [comment]
Tested in 4562_upgrade_flamingo branch and I can reproduce this issue. So re-opening..

**Comment by helenayele** [comment]
### Steps to reproduce:
1. load boat1.rep
2. Go to Time menu and change the display mode to Snail
3. Open Graph panel and expand it to the maximum height 
4. Minimize D-Light by Draging from bottom right to top left 
5. Then you will get  exceptions thrown.
https://screencast-o-matic.com/watch/cYV1l1vu5e

**Comment by ayeshare** [comment]
@helenayele @saulhidalgoaular I could reproduce this on develop as well with the same sequence.

**Comment by helenayele** [comment]
I can easily reproduce the Exception now following these steps :
1. Load boat1.rep
2. Draw graph and maximize the height of the graph
3. Drag from right bottom to top left to minimize D-Lite
4. This time there is not exception. 
5. Try to minimize the height of the graph and drag  d-Lite down to minimize its height.
6. Open Time menu and change the display mode to Snail.
This time you will see the below exception logged on the console. 
https://screencast-o-matic.com/watch/cYVuiGwV9W
But the exception stack traces are the following and a bit different from the above.
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mwc.debrief.lite.gui.GeoToolMapProjection.toWorld(GeoToolMapProjection.java:171)
	at Debrief.GUI.Tote.Painters.SnailDrawFix2.drawMe(SnailDrawFix2.java:370)
	at Debrief.GUI.Tote.Painters.SnailPainter2.highlightIt(SnailPainter2.java:274)
	at Debrief.GUI.Tote.Painters.SnailPainter2.newTime(SnailPainter2.java:399)
	at org.mwc.debrief.lite.DebriefLiteApp$7.refresh(DebriefLiteApp.java:902)
	at org.mwc.debrief.lite.DebriefLiteApp$ToteSetter.run(DebriefLiteApp.java:225)
	at org.mwc.debrief.lite.menu.DebriefRibbonTimeController$16.commandActivated(DebriefRibbonTimeController.java:825)
	at org.pushingpixels.flamingo.api.common.AbstractCommandButton.fireActionPerformed(AbstractCommandButton.java:673)
	at org.pushingpixels.flamingo.api.common.AbstractCommandButton$ActionHandler.actionPerformed(AbstractCommandButton.java:627)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at org.pushingpixels.flamingo.api.common.model.ActionToggleButtonModel.setPressed(ActionToggleButtonModel.java:128)
	at org.pushingpixels.flamingo.internal.ui.common.BasicCommandButtonListener.mouseReleased(BasicCommandButtonListener.java:128)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by IanMayo** [comment]
@helenayele - could you also re-check this please?

**Comment by helenayele** [comment]
Yes, still reproducible, the exception is logged continuously like :
[![Image from Gyazo](https://i.gyazo.com/4e0e59e5d26d7210289c31cdb3b706f7.gif)](https://gyazo.com/4e0e59e5d26d7210289c31cdb3b706f7)
The stack trace looks like 
[java.lang.NullPointerException.txt](https://github.com/debrief/debrief/files/4180251/java.lang.NullPointerException.txt)

**Comment by helenayele** [comment]
Yes, still reproducible, the exception is logged continuously like :
[![Image from Gyazo](https://i.gyazo.com/4e0e59e5d26d7210289c31cdb3b706f7.gif)](https://gyazo.com/4e0e59e5d26d7210289c31cdb3b706f7)
The stack trace looks like 
[java.lang.NullPointerException.txt](https://github.com/debrief/debrief/files/4180251/java.lang.NullPointerException.txt)

**Comment by helenayele** [comment]
The exception is no longer reproducible -  Verified.
