### ISSUE TITLE
NPE While loading sample.dpf file

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4760]
After loading a sample.dpf file , which was saved with Snail display mode, I get NPE loaded on the console and the positions are not loaded on the map panel.
[![Image from Gyazo](https://i.gyazo.com/90c28b56546dcbbbb9e923df50908066.png)](https://gyazo.com/90c28b56546dcbbbb9e923df50908066)

https://screencast-o-matic.com/watch/cYVUj6wfcA

Exception:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mwc.debrief.lite.gui.GeoToolMapProjection.toWorld(GeoToolMapProjection.java:171)
	at Debrief.GUI.Tote.Painters.SnailDrawFix2.drawMe(SnailDrawFix2.java:370)
	at Debrief.GUI.Tote.Painters.SnailPainter2.highlightIt(SnailPainter2.java:274)
	at Debrief.GUI.Tote.Painters.SnailPainter2.newTime(SnailPainter2.java:399)
	at Debrief.GUI.Tote.Painters.PainterManager.newTime(PainterManager.java:171)
	at org.mwc.debrief.lite.DebriefLiteApp.redoTimePainter(DebriefLiteApp.java:1646)
	at org.mwc.debrief.lite.DebriefLiteApp$20.run(DebriefLiteApp.java:1793)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[sample.zip](https://github.com/debrief/debrief/files/4126880/sample.zip)

**Comment by helenayele** [comment]
I get the same exception while adding Scale and Grid decorations as well

**Comment by helenayele** [comment]
Working fine - Verified.
