### ISSUE TITLE
Can't use SVG symbol for tracks in Debrief-Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4893]
I was just recording a demo video for Debrief-Lite.

I tried to set the set the tracks symbol to be one of the SVG shapes. But, Debrief fell over:
![image](https://user-images.githubusercontent.com/1108513/85019261-6f482100-b166-11ea-8eab-af3c2b10f27b.png)

There is a chance that we're not distributing the SVG shapes with Debrief-Lite.

**Comment by IanMayo** [comment]
@helenayele - would you mind seeing if you can reproduce this please?

If you can, could you create steps to reproduce, for @ayeshare ?

thanks.

**Comment by helenayele** [comment]
sure

**Comment by helenayele** [comment]
On production version of D-Lite, not possible to reproduce. 
[![Image from Gyazo](https://i.gyazo.com/399b369802720dff04d662c4730da196.png)](https://gyazo.com/399b369802720dff04d662c4730da196)

I am checking on the released version of D-Lite

**Comment by helenayele** [comment]
### Steps to Reproduce:
1. Launch D-Lite from command line using java -jar debrief-lite.jar 
2. Insert label
3. Open the label property window by double-clicking on the label shape from the outline panel
4. Change Symbol type with any of the shape that are prefixed by SVG:
[![Image from Gyazo](https://i.gyazo.com/b5405bace442113cad7caa022140d836.png)](https://gyazo.com/b5405bace442113cad7caa022140d836)
5. Select Apply
This time a bunch of exceptions are throw on the CMD and the symbol is not applied on the shape.

#### Stack trace:
INFO:  Exception caught:Failed to open SVG file svg:decoy_aw from /decoy_aw.svg
java.io.FileNotFoundException: svg:decoy_aw
        at MWC.GUI.Shapes.Symbols.SVG.SVGShape.getDocument(Unknown Source)
        at MWC.GUI.Shapes.Symbols.SVG.SVGShape.paint(Unknown Source)
        at MWC.GUI.Shapes.Symbols.SVG.SVGShape.paint(Unknown Source)
        at Debrief.Wrappers.LabelWrapper.paintMe(Unknown Source)
        at Debrief.Wrappers.LabelWrapper.paint(Unknown Source)
        at MWC.GUI.Plottables.paint(Unknown Source)
        at MWC.GUI.BaseLayer.paint(Unknown Source)
        at MWC.GUI.Layers.paint(Unknown Source)
        at org.mwc.debrief.lite.DebriefLiteApp.doPaint(Unknown Source)
        at org.mwc.debrief.lite.DebriefLiteApp$17.paint(Unknown Source)
        at org.mwc.debrief.lite.map.GeoToolMapRenderer.paintEvent(Unknown Source)
        at org.mwc.debrief.lite.map.LiteMapPane.paintComponent(Unknown Source)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
        at org.mwc.debrief.lite.map.LiteMapPane.paint(Unknown Source)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
        at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5262)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1707)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1616)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1060)
        at java.desktop/java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
        at java.desktop/sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:78)
        at java.desktop/sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:115)
        at java.desktop/java.awt.Container.paint(Container.java:2002)
        at java.desktop/java.awt.Window.paint(Window.java:3940)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:876)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
INFO:  Exception caught:Failed to parse SVG file for: svg:decoy_aw

**Comment by helenayele** [comment]
Works fine now.
[![Image from Gyazo](https://i.gyazo.com/512ec351794bf7abccab54098208cb4f.png)](https://gyazo.com/512ec351794bf7abccab54098208cb4f)
Verified
