### ISSUE TITLE
Operation failed Adding item to series error while inserting a row for the second time

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4894]
I get RuntimeException thrown while inserting a row of data from grid editor for the second time without editing the first added row.

### Steps:

1. Open boat1.rep file
2. Open Grid editor view
3. From Outline view, select 120500.00 layer, this time you will get data displayed in grid editor.
4. Go to the bottom or anywhere you want and select a row , and right click  and select Insert Row context menu
5. This time it adds a duplicate row. as of the selected row as new row.
6. Try to select the previous selected row and select again insert row context menu. This time it didn't add other row instead throws the below exception.

[![Image from Gyazo](https://i.gyazo.com/82579be53415fc49728e89ddb01733a6.gif)](https://gyazo.com/82579be53415fc49728e89ddb01733a6)

### Expected result:
Instead of logging the exception silently, it should inform the user that there is a duplicate row and can't insert this row again .

java.lang.RuntimeException: Operation failed Adding item to series
	at org.mwc.cmap.grideditor.table.actons.AbstractViewerAction.handleExecutionException(AbstractViewerAction.java:43)
	at org.mwc.cmap.grideditor.table.actons.AbstractViewerAction.run(AbstractViewerAction.java:60)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
Caused by: org.eclipse.core.commands.ExecutionException: While executing the operation, an exception occurred
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:503)
	at org.mwc.cmap.grideditor.table.actons.AbstractViewerAction.run(AbstractViewerAction.java:58)
	... 30 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 403
	at java.base/java.util.Vector.get(Vector.java:780)
	at org.mwc.cmap.grideditor.command.EnvironmentState$ItemAtKnownPosition.<init>(EnvironmentState.java:56)
	at org.mwc.cmap.grideditor.command.InsertItemOperation.doExecute(InsertItemOperation.java:52)
	at org.mwc.cmap.grideditor.command.AbstractGridEditorOperation.execute(AbstractGridEditorOperation.java:66)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:495)
	... 31 more

**Comment by saulhidalgoaular** [comment]
![image](https://user-images.githubusercontent.com/11049943/86128061-25095d00-bae1-11ea-88ab-7b8e4e0086ba.png)

Hello, the error happens because the item being cloned is taken as the "same item", and it is not inserted into the track. I will retake this ticket after finishing the Nisida ticket.

**Comment by helenayele** [comment]
Now able to add duplicate rows with no limit.
[![Image from Gyazo](https://i.gyazo.com/f7368af90d76fc70a31a44a00f486cd7.gif)](https://gyazo.com/f7368af90d76fc70a31a44a00f486cd7)
Verified
