### ISSUE TITLE
Adding invalid latitude/longitude values in the grid cells throws exception with error dialog

### ISSUE THREAD

**Issue by helenayele** [debrief/debrief#4898]
When we edit latitude and longitude with invalid values like 90, 78, etc , it throws java.lang.IllegalArgumentException: exception with error dialog.
[![Image from Gyazo](https://i.gyazo.com/1e20dbb1f63755c98e98045aa0d94cf8.gif)](https://gyazo.com/1e20dbb1f63755c98e98045aa0d94cf8)
And after this dialog is closed , if you click on any row , it logs multiple exceptions
[![Image from Gyazo](https://i.gyazo.com/2efde375230d784ded415e2ca04a870d.gif)](https://gyazo.com/2efde375230d784ded415e2ca04a870d)

Stack trace:
java.lang.IllegalArgumentException: Illegal value of minutes: 70.755
	at org.mwc.cmap.gridharness.data.base60.SexagesimalSupport.combineToDegrees(SexagesimalSupport.java:237)
	at org.mwc.cmap.gridharness.data.base60.Sexagesimal.getCombinedDegrees(Sexagesimal.java:40)
	at org.mwc.cmap.gridharness.views.WorldLocationCellEditor.doGetValue(WorldLocationCellEditor.java:156)
	at org.eclipse.jface.viewers.CellEditor.getValue(CellEditor.java:479)
	at org.eclipse.jface.viewers.EditingSupport.saveCellEditorValue(EditingSupport.java:115)
	at org.eclipse.jface.viewers.ColumnViewerEditor.saveEditorValue(ColumnViewerEditor.java:436)
	at org.eclipse.jface.viewers.ColumnViewerEditor.applyEditorValue(ColumnViewerEditor.java:302)
	at org.eclipse.jface.viewers.ColumnViewerEditor.handleEditorActivationEvent(ColumnViewerEditor.java:419)
	at org.eclipse.jface.viewers.ColumnViewer.triggerEditorActivationEvent(ColumnViewer.java:680)
	at org.eclipse.jface.viewers.ColumnViewer.handleMouseDown(ColumnViewer.java:655)
	at org.eclipse.jface.viewers.ColumnViewer.access$0(ColumnViewer.java:651)
	at org.eclipse.jface.viewers.ColumnViewer$1.mouseDown(ColumnViewer.java:100)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

**Comment by helenayele** [comment]
When user inserts invalid values, now it popups this dialog:
[![Image from Gyazo](https://i.gyazo.com/ed3027f4e1bed90725f5b0efeeab5b99.png)](https://gyazo.com/ed3027f4e1bed90725f5b0efeeab5b99)

Verified
