### ISSUE TITLE
Null Pointer Exception while Copying a FixWrapper

### ISSUE THREAD

**Issue by saulhidalgoaular** [debrief/debrief#4926]
Steps to reproduce:
1. Open the file `boat1.rep`
2. In the Outline, expand the Track Nelson, and the Fixes.
3. Right click over a Fix
4. Click `Copy` 

Error log.
```
!ENTRY org.mwc.cmap.core 1 0 2020-07-21 07:04:17.579
!MESSAGE Exception caught:null
!STACK 0
java.lang.NullPointerException
	at Debrief.Wrappers.FixWrapper.getTime(FixWrapper.java:1343)
	at Debrief.Wrappers.FixWrapper.compareTo(FixWrapper.java:1129)
	at MWC.GUI.PlainWrapper.compareTo(PlainWrapper.java:1)
	at MWC.GUI.Plottables$CompareEditables.compare(Plottables.java:201)
	at MWC.GUI.Plottables$CompareEditables.compare(Plottables.java:1)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:392)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.readObject(ConcurrentSkipListMap.java:1254)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2273)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor.cloneThis(RightClickCutCopyAdaptor.java:958)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor.cloneThese(RightClickCutCopyAdaptor.java:913)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor$CopyItem$1.doCopy(RightClickCutCopyAdaptor.java:116)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor$CopyItem$1.execute(RightClickCutCopyAdaptor.java:135)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:495)
	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:664)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor$CopyItem.run(RightClickCutCopyAdaptor.java:159)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
java.lang.NullPointerException
	at Debrief.Wrappers.FixWrapper.getTime(FixWrapper.java:1343)
	at Debrief.Wrappers.FixWrapper.compareTo(FixWrapper.java:1129)
	at MWC.GUI.PlainWrapper.compareTo(PlainWrapper.java:1)
	at MWC.GUI.Plottables$CompareEditables.compare(Plottables.java:201)
	at MWC.GUI.Plottables$CompareEditables.compare(Plottables.java:1)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:392)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.readObject(ConcurrentSkipListMap.java:1254)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2273)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2306)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2144)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1646)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:464)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor.cloneThis(RightClickCutCopyAdaptor.java:958)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor.cloneThese(RightClickCutCopyAdaptor.java:913)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor$CopyItem$1.doCopy(RightClickCutCopyAdaptor.java:116)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor$CopyItem$1.execute(RightClickCutCopyAdaptor.java:135)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:495)
	at org.mwc.cmap.core.CorePlugin.run(CorePlugin.java:664)
	at org.mwc.cmap.core.operations.RightClickCutCopyAdaptor$CopyItem.run(RightClickCutCopyAdaptor.java:159)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5874)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1400)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5138)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

```

**Comment by helenayele** [comment]
No such exception or other issues exist while using cu\copy\delete context menus.
[![Image from Gyazo](https://i.gyazo.com/9e501f9c15d846f0f9078c98f6962612.gif)](https://gyazo.com/9e501f9c15d846f0f9078c98f6962612)
Verified.
