### ISSUE TITLE
In GridEditor error from FixData rather than Sensor Data

### ISSUE THREAD

**Issue by ayeshare** [debrief/debrief#5102]
While addressing #5086, I found this error.

java.lang.IllegalArgumentException: Descriptor: Course(degs) is not applicable to item: class Debrief.Wrappers.SensorContactWrapper, there are no getters with name : getCourseDegs
	at org.mwc.cmap.grideditor.command.BeanUtil.getItemValue(BeanUtil.java:86)
	at org.mwc.cmap.grideditor.command.BeanUtil.getItemValue(BeanUtil.java:48)
	at org.mwc.cmap.grideditor.table.DescriptorEditingSupport.setValue(DescriptorEditingSupport.java:115)

This is what I did.  I updated the range value after selecting a set of sensor contacts to a new value.  The value didnt get reflected.  I closed and reopend the grid editor and then clicked positions and sensors.
The file used was sample_lots_of_sensors.dpf

**Comment by ayeshare** [comment]
This cannot be reproduced now
