### ISSUE TITLE
Natural Earth background vector data

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#984]
Natural Earth data is a publicly available, attract set of Vectored data (Shapefiles).  It's available at a set of 3 different resolutions (1:10M, 1:50M, 1:110M).  Since it's vectored data, covering just a few data-types, it's quite small.  It would be quite easy to distribute Debrief with all resolutions.

Once the "NaturalEarth" folder is specified, Debrief would extract the relevant resolutions and data-types, putting them into a data-structure able to determine which resolution to display, then render particular datasets in specified shading.  Properties would be provided to allow users to switch data-types on and off, with some elementary formatting options.

Here's a screenshot of maritime-related Natural Earth data, viewed in QGIS:
![naturalearthqgis](https://cloud.githubusercontent.com/assets/1108513/5360131/4737b740-7fba-11e4-9e30-5f14e470f0cd.png)

Note that the Natural Earth data doesn't come with styling (colors/line styles) so users will have to assign them, or we'll have to come up with some sensible defaults.  But, we can eye-drop the colors from the Natural Earth raster datasets - particularly for bathymetric datasets.

Here is how the Natural Earth decided to style their data:
![nev_10m_physical_2](https://cloud.githubusercontent.com/assets/1108513/5360160/70df3974-7fba-11e4-9434-a6b5d8799d5f.png)

I've recorded some design/implementation thoughts here:
https://github.com/debrief/debrief/wiki/Natural-Earth-background-ref-data

**Comment by pecko** [comment]
The commit https://github.com/pecko/debrief/commit/53b2b508a73c249abe0eef399f23006c3ba99e33 implements labels (polygons, points and lines labels if exists). I have tested only polygon labels (the name feature property) because I don't know if there is some dataset with points or line labels. 

There is a issue with font on Linux. The following is screenshot on Linux:

![labels](https://cloud.githubusercontent.com/assets/534584/5599533/05979676-92c9-11e4-97aa-a53aeb2fea9f.png)

It's fine on Windows:
![labelswindows1](https://cloud.githubusercontent.com/assets/534584/5599579/035654e6-92ca-11e4-8f1a-ee8c595a41c4.png)

Since, all is fine in standard geotools application on Linux, I will try to find what is wrong in Debrief on Linux.

**Comment by pecko** [comment]
I have solved the issue on Linux using a few rendering hints (GeoToolsPainter.drawAwtImage)
The commit: https://github.com/pecko/debrief/commit/5bc364f29ace76dfe4b159e7d8f8611cc5f557ad

I have isolated these hints only on Linux (for now). Screenshot:
![labelslinux](https://cloud.githubusercontent.com/assets/534584/5600465/b9007f64-92da-11e4-902a-e3d1b468cb22.png)

BTW
The StreamingRenderer renderer already paints labels based on visible polygon as required in https://github.com/debrief/debrief/issues/1000

**Comment by IanMayo** [comment]
Hey, good progress @pecko .

I think we've got a problem related to filtering data points.  The zero bathy layer covers the sea area between the coastline and the 200m contour.  This layer is shown correctly in the Southern Hemisphere, but not in the Northern Hemisphere (see attachment).

![zero_bathy](https://cloud.githubusercontent.com/assets/1108513/5611620/c09a6aae-94c0-11e4-8a4d-6b3842d02bd5.png)

The screenshot you provided in the previous issue shows this problem - where the white block of sea is shown next to France.

**Comment by pecko** [comment]
I have tested scanned image you sent me. Seems OK for me. I haven't faced the 90% exception.

Screenshot: (EPSG:4326) (new):
![scannedimage4326](https://cloud.githubusercontent.com/assets/534584/5630620/cf990e70-95bf-11e4-8946-5e84ced4fd85.png)

Screenshot (EPSG:3395) (old);
![scannedimage3395](https://cloud.githubusercontent.com/assets/534584/5630645/eb0252e8-95bf-11e4-958b-8c7aa29651e6.png)

However, I have faced the following exception:

Caused by: java.lang.ClassNotFoundException: com.sun.medialib.mlib.Image

Will open a new issue and add the required libraries.

**Comment by pecko** [comment]
@IanMayo comment from commit https://github.com/pecko/debrief/commit/2f19154a9dc1af3a1216cbc6c469b22bf6481b24

Unfortunately, when I view Tiff map images, they show once, then fail (see below).

I *think* that the TIF chart images are all in 3395, and if we use 3395 as our map projection, they don't have to be reprojected.  This means their proportions look "unchanged" on screen.

But, if we switch to another projection, Java has to "re-project" the image to fit in with the rest of the displayed data.  Currently we're failing because Java is missing a lib.  I expect we can resolve that.  But, once it is resolved, there is a chance that the chart images will look distorted.  Sadly, we won't know until we solve the first issue.  Aaah, maybe I can investigate their re-projected appearance in QGis.  *Issue for Ian*

````
Error: Could not find mediaLib accelerator wrapper classes. Continuing in pure Java mode.
Occurs in: com.sun.media.jai.mlib.MediaLibAccessor
java.lang.NoClassDefFoundError: com/sun/medialib/mlib/Image
	at com.sun.media.jai.mlib.MediaLibAccessor$1.run(MediaLibAccessor.java:248)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.media.jai.mlib.MediaLibAccessor.setUseMlib(MediaLibAccessor.java:245)
	at com.sun.media.jai.mlib.MediaLibAccessor.useMlib(MediaLibAccessor.java:177)
	at com.sun.media.jai.mlib.MediaLibAccessor.isMediaLibCompatible(MediaLibAccessor.java:357)
	at com.sun.media.jai.mlib.MediaLibAccessor.isMediaLibCompatible(MediaLibAccessor.java:315)
	at com.sun.media.jai.mlib.MlibWarpRIF.create(MlibWarpRIF.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.media.jai.FactoryCache.invoke(FactoryCache.java:122)
	at javax.media.jai.OperationRegistry.invokeFactory(OperationRegistry.java:1674)
	at javax.media.jai.ThreadSafeOperationRegistry.invokeFactory(ThreadSafeOperationRegistry.java:473)
	at javax.media.jai.registry.RIFRegistry.create(RIFRegistry.java:332)
	at javax.media.jai.RenderedOp.createInstance(RenderedOp.java:819)
	at javax.media.jai.RenderedOp.createRendering(RenderedOp.java:867)
	at javax.media.jai.RenderedOp.getRendering(RenderedOp.java:888)
	at javax.media.jai.RenderedOp$1.getPropertyNames(RenderedOp.java:1791)
	at javax.media.jai.PropertyEnvironment.mapDefaults(PropertyEnvironment.java:270)
	at javax.media.jai.PropertyEnvironment.getPropertyNames(PropertyEnvironment.java:125)
	at javax.media.jai.WritablePropertySourceImpl.addProperties(WritablePropertySourceImpl.java:298)
	at javax.media.jai.RenderedOp.createPropertySource(RenderedOp.java:1817)
	at javax.media.jai.RenderedOp.setProperty(RenderedOp.java:2034)
	at org.geotools.coverage.processing.operation.Resampler2D.reproject(Resampler2D.java:716)
	at org.geotools.coverage.processing.operation.Resample.doOperation(Resample.java:258)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRendererUtilities.reproject(GridCoverageRendererUtilities.java:325)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.reproject(GridCoverageRenderer.java:479)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.renderImage(GridCoverageRenderer.java:782)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.paint(GridCoverageRenderer.java:992)
	at org.geotools.renderer.lite.StreamingRenderer$RenderCoverageReaderRequest.execute(StreamingRenderer.java:3449)
	at org.geotools.renderer.lite.StreamingRenderer$PainterThread.run(StreamingRenderer.java:3533)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.sun.medialib.mlib.Image
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 37 more
````

**Comment by pecko** [comment]
The "java.lang.ClassNotFoundException: com.sun.medialib.mlib.Image" exception can be disabled by

System.setProperty("com.sun.media.jai.disableMediaLib", "true");

However, after that I get the following exception:

Jan 06, 2015 6:05:00 PM org.geotools.factory.FactoryRegistry scanForPlugins
WARNING: Can't load a service for category "Operation". Cause is "ServiceConfigurationError: org.opengis.coverage.processing.Operation: Provider org.geotools.coverage.processing.operation.ZonalStats could not be instantiated".
java.util.ServiceConfigurationError: org.opengis.coverage.processing.Operation: Provider org.geotools.coverage.processing.operation.ZonalStats could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:224)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:377)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at org.geotools.factory.FactoryRegistry.register(FactoryRegistry.java:826)
	at org.geotools.factory.FactoryRegistry.scanForPlugins(FactoryRegistry.java:772)
	at org.geotools.factory.FactoryRegistry.scanForPluginsIfNeeded(FactoryRegistry.java:805)
	at org.geotools.factory.FactoryRegistry.getServiceProviders(FactoryRegistry.java:196)
	at org.geotools.coverage.processing.CoverageProcessor.scanForPlugins(CoverageProcessor.java:578)
	at org.geotools.coverage.processing.CoverageProcessor.getOperation(CoverageProcessor.java:455)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageReaderHelper.<clinit>(GridCoverageReaderHelper.java:70)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.renderImage(GridCoverageRenderer.java:757)
	at org.geotools.renderer.lite.gridcoverage2d.GridCoverageRenderer.paint(GridCoverageRenderer.java:992)
	at org.geotools.renderer.lite.StreamingRenderer$RenderCoverageReaderRequest.execute(StreamingRenderer.java:3449)
	at org.geotools.renderer.lite.StreamingRenderer$PainterThread.run(StreamingRenderer.java:3533)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/jaitools/media/jai/zonalstats/ZonalStatsDescriptor
	at org.geotools.coverage.processing.operation.ZonalStats.<clinit>(ZonalStats.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:373)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.jaitools.media.jai.zonalstats.ZonalStatsDescriptor
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 24 more

Checking...

**Comment by pecko** [comment]
I will postpone the issue related to CNFE com.sun.medialib.mlib.Image. It is just warning and logged once. I don't have better solution for now.

@IanMayo Please advice what to do related to ESPG projections?

**Comment by pecko** [comment]
Currently, it is not possible to see Natural Earth and TIFF layer in the same moment.

**Comment by IanMayo** [comment]
Yes, I understand.  I'm now on #1021 tomorrow morning, but this Projection issue remains my main priority after that.  I do hope we can fix for NE data to display under the old Projection.

**Comment by pecko** [comment]
OK. I will try to fix #1022 for today.

**Comment by pecko** [comment]
I have made some changes via https://github.com/pecko/debrief/commit/5519430f31290e00dc3944944fe2cb8e8e9d56f4

@IanMayo  Could you please review? It isn't finished but maybe looks better. 

Seems that the Debrief convert image to ESPG:3395 and do reverse in GtProjection. 
qgis recognize the image's projection as EPSG:54004 - World_Mercator 
I have also tried to convert it to EPSG:4326 using the gdalwarp utility (will send you both images via email):

**Comment by pecko** [comment]
BTW, the TIF image disappears when adding NE layer. Deleting/setting invisible of NE Layer doesn't help.
@IanMayo Do you know why? Would you like me to investigate?

**Comment by pecko** [comment]
The https://github.com/pecko/debrief/commit/8838955271b178a9d58f4799e33d1fee06b15d17 commit fixes the issue with painting TIF image and NE Layer.
I have removed disposing geotools map, but it has to be disposed in some moment. Will check again when fixing https://github.com/debrief/debrief/issues/1016 (Natural Earth - move away from setMap usage)

**Comment by pecko** [comment]
@IanMayo I'm playing with the projections, but would like that you test current issue984_gtrenderer branch. Currently, the Debrief uses the ESPG:4326 projection. (I know what you want and will try to use ESPG:3395, but have to first make good reprojection).
However, it looks good for me.
Notice: when rendering a TIF image, geotools searches for the file with suffix *prj (2_BRITISH_ISLES.prj in our case) and use projection described here (it is simple text file). You will see that it's painted differently depend on this file exists or not in this directory. The issue984_gtrenderer branch shows this TIF better when you import this file too.

**Comment by IanMayo** [comment]
ok, i'm on this in the morning
​

**Comment by pecko** [comment]
I have made a few screenshots:

NE and TIF
![proj1](https://cloud.githubusercontent.com/assets/534584/5672436/96c718ee-9790-11e4-8c5f-132005d06eda.png)

NE (TIF hidden) - the UK border is painted correctly
![proj2](https://cloud.githubusercontent.com/assets/534584/5672458/baf99afc-9790-11e4-94e1-016d6dcf7283.png)

Unfortunately we still have white area with bathy zero:

![proj4](https://cloud.githubusercontent.com/assets/534584/5672476/e9b4e8b0-9790-11e4-89df-730e3736d62a.png)

TIF text currently (ESPG:4326 and there is *prj file)

![proj5](https://cloud.githubusercontent.com/assets/534584/5672489/036ff420-9791-11e4-82b7-ab289117bcb8.png)

**Comment by pecko** [comment]
There are some white area when using standard geotools application:

![proj3](https://cloud.githubusercontent.com/assets/534584/5672597/093b5312-9792-11e4-901f-69bb0e5d8acf.png)

**Comment by pecko** [comment]
No white area in QGis
![proj6](https://cloud.githubusercontent.com/assets/534584/5672740/9cc5a3e8-9793-11e4-9033-6ab445ac406d.png)

**Comment by IanMayo** [comment]
Don't worry about those last white areas, that's intended behaviour.

What? Intended behaviour? Don't be crazy Ian!

In the Debrief shot you're showing the 0m Bathy at 10M resolution, but your showing the Countries at 50M resolution.  The 50M resolution is more coarse, so gaps are left.

In the QGis shot both datasets are at 10M resolution - so they join tidily.

**Comment by pecko** [comment]
> In the Debrief shot you're showing the 0m Bathy at 10M resolution, but your showing the Countries at 
> 50M resolution. The 50M resolution is more coarse, so gaps are left.

Great.

I will check difference in TIF with and without NE.

Do you mean that we have correct main behavior for TIFF and NE so I can can focus on the performance?

**Comment by IanMayo** [comment]
Yes, I'm happy that the current NE/TIFF capabilities work - and you can move on to the performance.

I remain nervous that the TIFFs are stretched, but lets defer that for another time.

**Comment by pecko** [comment]
> He's now got a new problem. If we don't have NE data shown, the TIFF image has holes in it. Pure 
> black dots aren't shown

That is the same in the master branch, so it isn't a new issue.
BTW I have also reproduced CNFE in the master branch. It is fixed in the issue984_gtrenderer branch.

**Comment by IanMayo** [comment]
I think I went back to July and it worked ok. Well try to find working
commit layer.

**Comment by pecko** [comment]
OK. I have merged https://github.com/pecko/debrief/pull/6 to the issue984_gtrenderer

**Comment by pecko** [comment]
> I think I went back to July and it worked ok.

It is the same in QGis, so I suppose you have had another image.

**Comment by pecko** [comment]
I think that you set ne_110m_admin_0_countries in the 50m group.

**Comment by IanMayo** [comment]
Sam, one more feature for this please.  I'd like to introduce icons in the UI for natural earth (I've put the icons into the plugin in the 984_gtrender_refactor branch).

I'd like the icons to be used in this way, please:
* Introduce a new **Chart Features** group in the toolbar, immediately before the **Drawing** items. This will be called **toolbar:org.mwc.debrief.core.EditorShapes**.  (This change will be implemented in the debrief.core plugin)
* 16 px NE icon in the **Chart Features** menu (this will be in the NE plugin)
* Put the 24 px NE icon into this new toolbar grouping  (this will be in the NE plugin)

**Comment by pecko** [comment]
> Introduce a new Chart Features group in the toolbar, immediately before the Drawing items. This will 
> be called toolbar:org.mwc.debrief.core.EditorShapes. (This change will be implemented in the 
> debrief.core plugin)
 
I suppose you mean toolbar:org.mwc.debrief.core.ChartFeatures, because we already have toolbar:org.mwc.debrief.core.EditorShapes group.

The commit: https://github.com/pecko/debrief/commit/b110ab820e9fcb436f410a0809345fe00b3c0d55
The branch: https://github.com/pecko/debrief/tree/issue984_naturalearth

The screenshot:

![neicon](https://cloud.githubusercontent.com/assets/534584/5926943/39ca3a52-a66f-11e4-89c6-5fd2616b8281.png)

**Comment by pecko** [comment]
I have also updated the reset perspective flag so when starting a distribution, the perspective will be reset automatically and a new icon/action will be shown.

**Comment by IanMayo** [comment]
"Reset perspective flag" - hey, that was clever. I'd completely forgotten about that ;-)

**Comment by IanMayo** [comment]
[Test message for Daria, please ignore]

**Comment by IanMayo** [comment]
We're on top of this now.
